common:
  gauge_root: &gauge_root /tmp/gauge-root
  gauge_home: &gauge_home /tmp/gauge-home
  timer_spec: &timer_spec "0 30 17 ? * MON-FRI"
  build_artifacts: &build_artifacts
    - build:
        source: gauge-tests/reports-#{language}/html-report/*
        destination: html-report
    - build:
        source: gauge-tests/reports-#{language}/xml-report/*
        destination: xml-report
    - build:
        source: gauge-tests/testLogs
        destination: test-logs
  install_gauge_released: &install_gauge_released
    - exec:
        command: /bin/bash
        arguments:
          - -c
          - curl -SsL https://downloads.gauge.org/stable | sh -s -- --location=$GAUGE_ROOT
  gauge_install_runner_nightly: &gauge_install_runner_nightly
    - exec:
        command: /bin/sh
        arguments:
          - -c
          - "($GAUGE_ROOT/gauge config gauge_repository_url https://raw.githubusercontent.com/getgauge/gauge-nightly-repository/master/ && $GAUGE_ROOT/gauge install #{language} && $GAUGE_ROOT/gauge version)"
  gauge_install_released_plugins: &gauge_install_released_plugins
    - exec:
        working_directory: gauge-tests
        command: /bin/sh
        arguments:
          - -c
          - "($GAUGE_ROOT/gauge config gauge_repository_url https://downloads.gauge.org/plugin && $GAUGE_ROOT/gauge install && $GAUGE_ROOT/gauge version)"
  run_fts: &run_fts
    - exec:
        working_directory: gauge-tests
        command: /bin/sh
        arguments:
          - -c
          - "PATH=$PATH:$GAUGE_ROOT mvn -q clean install -Denv=ci-#{language} -Dtags=\"#{language}\""
  clean_gauge_directories: &clean_gauge_directories
    - exec:
        command: /bin/sh
        arguments:
          - -c
          - "rm -rf $GAUGE_ROOT $GAUGE_HOME | ls && mkdir $GAUGE_ROOT $GAUGE_HOME"

pipelines:
  Gauge_Released_Java_Nightly:
    group: Build_Matrix
    timer:
      spec: *timer_spec
      only_on_changes: yes
    parameters:
      language: java
    materials:
      gauge-tests:
        git: https://github.com/getgauge/gauge-tests.git
        destination: gauge-tests
        autoUpdate: false
      java-nightly:
        pipeline: Gauge-Java-Nightly
        stage: PushToBintray
    stages:
      - specs:
          clean_workspace: true
          approval: manual
          jobs:
            darwin:
              environment_variables:
                GAUGE_ROOT: *gauge_root
                GAUGE_HOME: *gauge_home
              resources:
                - FT
                - darwin
              tasks:
                - *clean_gauge_directories
                - *install_gauge_released
                - *gauge_install_runner_nightly
                - *gauge_install_released_plugins
                - *run_fts
              artifacts: *build_artifacts
  Gauge_Released_Ruby_Nightly:
    group: Build_Matrix
    timer:
      spec: *timer_spec
      only_on_changes: yes
    parameters:
      language: ruby
    materials:
      gauge-tests:
        git: https://github.com/getgauge/gauge-tests.git
        destination: gauge-tests
        autoUpdate: false
      ruby-nightly:
        pipeline: Gauge-Ruby-Nightly
        stage: PushToBintray
    stages:
      - specs:
          clean_workspace: true
          approval: manual
          jobs:
            darwin:
              environment_variables:
                GAUGE_ROOT: *gauge_root
                GAUGE_HOME: *gauge_home
              resources:
                - FT
                - darwin
              tasks:
                - *clean_gauge_directories
                - *install_gauge_released
                - *gauge_install_runner_nightly
                - *gauge_install_released_plugins
                - *run_fts
              artifacts: *build_artifacts
