pipelines:
  Common-New:
    group: Misc
    materials:
      common:
        git: https://github.com/getgauge/common.git
    stages:
      - test:
          jobs:
            linux:
              elastic_profile_id: centos-all
              environment_variables:
                GOPATH : /tmp
              tasks:
                - exec:
                    command: /bin/sh
                    arguments:
                      - -c
                      - rm -rf $GOPATH/src
                - exec:
                    command: go
                    arguments:
                      - get
                      - -d
                      - -u
                      - -t
                      - github.com/getgauge/common
                - exec:
                    command: go
                    arguments:
                      - test
                      - -v
                      - github.com/getgauge/common