pipelines:
  dotnet-build:
    group: Gauge-Dotnet
    materials:
      dotnet:
        git: https://github.com/getgauge/gauge-dotnet.git
    stages:
      - build:
          jobs:
            unit-test:
              elastic_profile_id: windows-all
              tasks:
               - exec:
                   command: run
                   arguments:
                    - test
  dotnet-package:
    group: Gauge-Dotnet
    materials:
      dotnet:
        git: https://github.com/getgauge/gauge-dotnet.git
      upstream:
        pipeline: dotnet-build
        stage: build
    stages:
      - artifact:
          jobs:
            installer:
              resources:
               - darwin
               - FT
              tasks:
               - exec:
                   command: /bin/sh
                   arguments:
                    - run.sh
                    - package
              artifacts:
               - build:
                   source: artifacts/
  dotnet-FT:
    group: Gauge-Dotnet
    materials:
      gauge-tests:
        git: https://github.com/getgauge/gauge-tests.git
      package:
        pipeline: dotnet-package
        stage: artifact
      gauge:
        pipeline: Gauge-Build
        stage: windows
    environment_variables:
      enable_multithreading: true
    stages:
      - build:
          clean_workspace: true
          jobs:
            windows:
              elastic_profile_id: windows-all
              environment_variables:
                GAUGE_ROOT: C:\gauge_root
                GAUGE_HOME: C:\gauge_plugins
                DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
              tasks:
               - fetch:
                   pipeline: Gauge-Build
                   stage: windows
                   job: sign
                   is_file: yes
                   source: test_installers/gauge-windows.x86_64.zip
               - fetch:
                   pipeline: dotnet-package
                   stage: artifact
                   job: installer
                   source: artifacts
               - exec:
                   command: cmd
                   arguments:
                    - /c
                    - "unzip -o gauge-windows.x86_64.zip -d %GAUGE_ROOT%"
               - exec:
                   command: cmd
                   arguments:
                    - /c
                    - "%GAUGE_ROOT%/gauge"
                    - config
                    - gauge_repository_url
                    - https://raw.githubusercontent.com/getgauge/gauge-nightly-repository/master/
               - exec:
                   command: cmd
                   arguments:
                    - /c
                    - "%GAUGE_ROOT%/gauge"
                    - uninstall
                    - dotnet
               - exec:
                   working_directory: artifacts
                   command: cmd
                   arguments:
                    - /c
                    - "for %f in (gauge-dotnet*.zip) do %GAUGE_ROOT%/gauge install dotnet -f %f"
               - exec:
                   command: cmd
                   arguments:
                    - /c
                    - "%GAUGE_ROOT%/gauge"
                    - install
               - exec:
                    command: cmd
                    arguments:
                    - /c
                    - path %GAUGE_ROOT%;%PATH% & mvn -q clean test-compile gauge:execute -Denv=ci-dotnet -Dtags=csharp -DinParallel=true -Dnodes=3
               - exec:
                    run_if: any
                    command: cmd
                    arguments:
                    - /c
                    - del %GAUGE_ROOT%\gauge
               - exec:
                    run_if: any
                    command: cmd
                    arguments:
                    - /c
                    - del /q %GAUGE_HOME%\*
              artifacts:
                - build:
                    source: logs
                    destination: logs
            osx:
              resources:
                - darwin
                - FT
              environment_variables:
                GAUGE_ROOT: /tmp
              tasks:
                - fetch:
                    pipeline: Gauge-Build
                    stage: windows
                    job: sign
                    is_file: yes
                    source: test_installers/gauge-darwin.x86_64.zip
                - fetch:
                    pipeline: dotnet-package
                    stage: artifact
                    job: installer
                    source: artifacts
                - exec:
                    command: /bin/bash
                    arguments:
                    - -c
                    - mkdir -p $GAUGE_ROOT/bin && unzip -o gauge-darwin.x86_64.zip -d $GAUGE_ROOT/bin
                - exec:
                    command: /bin/bash
                    arguments:
                    - -c
                    - $GAUGE_ROOT/bin/gauge uninstall dotnet
                - exec:
                    working_directory: artifacts
                    command: /bin/sh
                    arguments:
                    - -c
                    - (version=$(ls gauge-dotnet-*.zip | sed "s/^gauge-dotnet-\([^;]*\).zip/\1/"); $GAUGE_ROOT/bin/gauge install dotnet -f gauge-dotnet-$version.zip)
                - exec:
                    command: /bin/sh
                    arguments:
                    - -c
                    - $GAUGE_ROOT/bin/gauge install
                - exec:
                    command: /bin/sh
                    arguments:
                      - -c
                      - PATH=$PATH:/tmp/bin mvn -q clean test-compile gauge:execute -Denv=ci-dotnet -Dtags=csharp
              artifacts:
                - build:
                    source: logs
                    destination: logs
  dotnet-LSP:
    group: Gauge-Dotnet
    materials:
      gauge-tests:
        git: https://github.com/getgauge/gauge-lsp-tests.git
      package:
        pipeline: dotnet-package
        stage: artifact
      gauge:
        pipeline: Gauge-Build
        stage: windows
    stages:
      - build:
          clean_workspace: true
          jobs:
            windows:
              elastic_profile_id: windows-all
              environment_variables:
                GAUGE_ROOT: C:\gauge_root
              tasks:
               - fetch:
                   pipeline: Gauge-Build
                   stage: windows
                   job: sign
                   is_file: yes
                   source: test_installers/gauge-windows.x86_64.zip
               - fetch:
                   pipeline: dotnet-package
                   stage: artifact
                   job: installer
                   source: artifacts
               - exec:
                   command: cmd
                   arguments:
                    - /c
                    - "unzip -o gauge-windows.x86_64.zip -d %GAUGE_ROOT%"
               - exec:
                   command: cmd
                   arguments:
                    - /c
                    - "%GAUGE_ROOT%/gauge"
                    - version
               - exec:
                   command: cmd
                   arguments:
                    - /c
                    - "npm"
                    - version
               - exec:
                   command: cmd
                   arguments:
                    - /c
                    - "%GAUGE_ROOT%/gauge"
                    - uninstall
                    - dotnet
               - exec:
                   working_directory: artifacts
                   command: cmd
                   arguments:
                    - /c
                    - "for %f in (gauge-dotnet*.zip) do %GAUGE_ROOT%/gauge install dotnet -f %f"
               - exec:
                   command: cmd
                   arguments:
                    - /c
                    - "%GAUGE_ROOT%/gauge config gauge_repository_url https://raw.githubusercontent.com/getgauge/gauge-nightly-repository/master"
               - exec:
                   command: cmd
                   arguments:
                    - /c
                    - "%GAUGE_ROOT%/gauge install"
               - exec:
                   command: cmd
                   arguments:
                    - /c
                    - "%GAUGE_ROOT%/gauge version"
               - exec:
                   command: cmd
                   arguments:
                    - /c
                    - npm
                    - install
               - exec:
                    command: cmd
                    arguments:
                    - /c
                    - path %GAUGE_ROOT%;%PATH% & gauge run specs --tags=!knownIssue --env=dotnet-wd
               - exec:
                    run_if: any
                    command: cmd
                    arguments:
                    - /c
                    - del %GAUGE_ROOT%\gauge
              artifacts:
                - build:
                    source: logs
                    destination: logs
            osx:
              resources:
                - darwin
                - FT
              environment_variables:
                GAUGE_ROOT: /tmp
              tasks:
                - fetch:
                    pipeline: Gauge-Build
                    stage: windows
                    job: sign
                    is_file: yes
                    source: test_installers/gauge-darwin.x86_64.zip
                - fetch:
                    pipeline: dotnet-package
                    stage: artifact
                    job: installer
                    source: artifacts
                - exec:
                    command: /bin/bash
                    arguments:
                    - -c
                    - mkdir -p $GAUGE_ROOT/bin && unzip -o gauge-darwin.x86_64.zip -d $GAUGE_ROOT/bin
                - exec:
                    command: /bin/bash
                    arguments:
                    - -c
                    - $GAUGE_ROOT/bin/gauge uninstall dotnet
                - exec:
                    working_directory: artifacts
                    command: /bin/sh
                    arguments:
                    - -c
                    - (version=$(ls gauge-dotnet-*.zip | sed "s/^gauge-dotnet-\([^;]*\).zip/\1/"); $GAUGE_ROOT/bin/gauge install dotnet -f gauge-dotnet-$version.zip)
                - exec:
                    command: /bin/sh
                    arguments:
                    - -c
                    - $GAUGE_ROOT/bin/gauge config gauge_repository_url https://raw.githubusercontent.com/getgauge/gauge-nightly-repository/master
                - exec:
                    command: /bin/sh
                    arguments:
                    - -c
                    - $GAUGE_ROOT/bin/gauge install
                - exec:
                    command: /bin/sh
                    arguments:
                    - -c
                    - $GAUGE_ROOT/bin/gauge version
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - npm install
                - exec:
                    command: /bin/sh
                    arguments:
                      - -c
                      - PATH=$PATH:/tmp/bin gauge run specs --env=dotnet-wd --tags=\!knownIssue
              artifacts:
                - build:
                    source: logs
                    destination: logs
  dotnet-release:
    group: Gauge-Dotnet
    materials:
      package:
        pipeline: dotnet-package
        stage: artifact
      dotnet-FT:
        pipeline: dotnet-FT
        stage: build
    stages:
      - release:
          approval: manual
          jobs:
            github:
              elastic_profile_id: centos-all
              environment_variables:
                repoName: gauge-dotnet
                GOPATH: /tmp
              secure_variables:
                GITHUB_TOKEN: NQJXCgXvHwzebDC27DfhkpsmjcMjRNwbguFJXdMvVXJyw5eSaKXE2EFPgji/6/ug
              tasks:
                - fetch:
                   pipeline: dotnet-package
                   stage: artifact
                   job: installer
                   source: artifacts
                - exec:
                   command: ls
                   working_directory: artifacts
                   arguments:
                    - -ltr
                - exec:
                   command: /bin/sh
                   working_directory: artifacts
                   arguments:
                    - -c
                    - (curl -sSfL https://github.com/getgauge/gauge/raw/master/build/github_release.sh | sh)
