common:
  build_artifacts: &build_artifacts
    - build:
        source: gauge-tests/reports-#{language}/html-report/*
        destination: html-report
    - build:
        source: gauge-tests/reports-#{language}/xml-report/*
        destination: xml-report
    - build:
        source: gauge-tests/testLogs
        destination: test-logs
  install_gauge: &install_gauge
    - fetch:
        pipeline: Gauge-Build
        stage: windows
        job: sign
        source: test_installers/gauge-darwin.x86_64.zip
        is_file: yes
    - exec:
        command: /bin/bash
        arguments:
          - -c
          - mkdir -p $GAUGE_ROOT/bin && unzip -o gauge-darwin.x86_64.zip -d $GAUGE_ROOT/bin
  install_html_report: &install_html_report
    - exec:
        command: /bin/sh
        arguments:
          - -c
          - ($GAUGE_ROOT/bin/gauge uninstall html-report)
    - fetch:
        pipeline: HTML_Report
        stage: package
        job: package
        source: deploy
    - exec:
        working_directory: deploy
        command: /bin/sh
        arguments:
        - -c
        - (version=$(ls html-report-*-darwin.x86_64.zip | sed "s/^html-report-\([^;]*\)-darwin.x86_64.zip/\1/"); $GAUGE_ROOT/bin/gauge install html-report -f html-report-$version-darwin.x86_64.zip)
  install_xml_report: &install_xml_report
    - exec:
        command: /bin/sh
        arguments:
          - -c
          - ($GAUGE_ROOT/bin/gauge uninstall xml-report)
    - fetch:
        pipeline: XML_Report
        stage: package
        job: package
        source: deploy
    - exec:
        working_directory: deploy
        command: /bin/sh
        arguments:
          - -c
          - (version=$(ls xml-report-*-darwin.x86_64.zip | sed "s/^xml-report-\([^;]*\)-darwin.x86_64.zip/\1/"); $GAUGE_ROOT/bin/gauge install xml-report -f xml-report-$version-darwin.x86_64.zip)

pipelines:
  temp_java_ft:
    group: Gauge-Java
    parameters:
      language: java
    materials:
      package:
        pipeline: Java-Build
        stage: package
      gauge-tests:
        git: https://github.com/getgauge/gauge-tests.git
        destination: gauge-tests
      gauge:
        pipeline: Gauge-Build
        stage: windows
      html-report:
        pipeline: HTML_Report
        stage: package
      xml-report:
        pipeline: XML_Report
        stage: package
    environment_variables:
      enable_multithreading: true
      language: java
    stages:
      - specs:
          clean_workspace: true
          jobs:
            darwin:
              environment_variables:
                GAUGE_ROOT: /tmp
                GAUGE_HOME: /tmp
              resources:
                - FT
                - darwin
              tasks:
                - *install_gauge
                - exec:
                    command: /bin/sh
                    arguments:
                      - -c
                      - ($GAUGE_ROOT/bin/gauge uninstall java)
                - fetch:
                    pipeline: Java-Build
                    stage: package
                    job: distro
                    source: deploy
                - exec:
                    working_directory: deploy
                    command: /bin/sh
                    arguments:
                    - -c
                    - (version=$(ls gauge-java-*-darwin.x86_64.zip | sed "s/^gauge-java-\([^;]*\)-darwin.x86_64.zip/\1/"); $GAUGE_ROOT/bin/gauge install java -f gauge-java-$version-darwin.x86_64.zip)
                - *install_html_report
                - *install_xml_report
                - exec:
                    working_directory: gauge-tests
                    command: /bin/sh
                    arguments:
                      - -c
                      - source $HOME/.jabba/jabba.sh && jabba use openjdk@1.10.0 && PATH=$PATH:$GAUGE_ROOT/bin mvn -q clean install -Denv=ci-java -Dtags="java"
              artifacts: *build_artifacts
