common:
  pipeline_materials: &pipeline_materials
    gauge-tests:
      git: https://github.com/getgauge/gauge-tests.git
      destination: gauge-tests
    package:
      pipeline: #{upstream_pipeline}
      stage: #{upstream_pipeline_stage}
    gauge:
      pipeline: Gauge-Build
      stage: windows
    html-report:
      pipeline: HTML_Report
      stage: package
    xml-report:
      pipeline: XML_Report
      stage: package
  build_artifacts: &build_artifacts
    - build:
        source: gauge-tests/reports-java/html-report/*
        destination: html-report
    - build:
        source: gauge-tests/reports-java/xml-report/*
        destination: xml-report
    - build:
        source: gauge-tests/testLogs
        destination: test-logs
  install_gauge_binary_darwin: &install_gauge_binary_darwin
    - fetch:
        pipeline: Gauge-Build
        stage: windows
        job: sign
        source: test_installers/gauge-darwin.x86_64.zip
        is_file: yes
    - exec:
        command: /bin/bash
        arguments:
          - -c
          - mkdir -p $GAUGE_ROOT/bin && unzip -o gauge-darwin.x86_64.zip -d $GAUGE_ROOT/bin
  install_html_plugin_darwin: &install_html_plugin_darwin
    - exec:
        command: /bin/sh
        arguments:
          - -c
          - ($GAUGE_ROOT/bin/gauge uninstall html-report)
    - fetch:
        pipeline: HTML_Report
        stage: package
        job: package
        source: deploy
    - exec:
        working_directory: deploy
        command: /bin/sh
        arguments:
        - -c
        - (version=$(ls html-report-*-darwin.x86_64.zip | sed "s/^html-report-\([^;]*\)-darwin.x86_64.zip/\1/"); $GAUGE_ROOT/bin/gauge install html-report -f html-report-$version-darwin.x86_64.zip)
  install_xml_plugin_darwin: &install_xml_plugin_darwin
    - exec:
        command: /bin/sh
        arguments:
          - -c
          - ($GAUGE_ROOT/bin/gauge uninstall xml-report)
    - fetch:
        pipeline: XML_Report
        stage: package
        job: package
        source: deploy
    - exec:
        working_directory: deploy
        command: /bin/sh
        arguments:
          - -c
          - (version=$(ls xml-report-*-darwin.x86_64.zip | sed "s/^xml-report-\([^;]*\)-darwin.x86_64.zip/\1/"); $GAUGE_ROOT/bin/gauge install xml-report -f xml-report-$version-darwin.x86_64.zip)
  install_language_plugin_darwin: &install_language_plugin_darwin
    - exec:
        command: /bin/sh
        arguments:
          - -c
          - ($GAUGE_ROOT/bin/gauge uninstall java)
    - exec:
        working_directory: deploy
        command: /bin/sh
        arguments:
        - -c
        - (version=$(ls gauge-java-*-darwin.x86_64.zip | sed "s/^gauge-java-\([^;]*\)-darwin.x86_64.zip/\1/"); $GAUGE_ROOT/bin/gauge install java -f gauge-java-$version-darwin.x86_64.zip)
  execute_fts: &execute_fts
    - exec:
        working_directory: gauge-tests
        command: /bin/sh
        arguments:
          - -c
          - mvn -q clean install -Denv=ci-java -Dtags="java"

pipelines:
  temp_java_ft:
    group: Gauge-Java
    parameters:
      upstream_pipeline: Java-Build
      upstream_pipeline_stage: package
      language: java
    materials: *pipeline_materials      
    environment_variables:
      enable_multithreading: true
      language: java
    stages:
      - specs:
          clean_workspace: true
          jobs:
            darwin:
              environment_variables:
                GAUGE_ROOT: ./gauge_bin
                GAUGE_HOME: ./gauge_bin
              resources:
                - FT
                - darwin
              tasks:
                - *install_gauge_binary_darwin
                - *install_html_plugin_darwin
                - *install_xml_plugin_darwin
                - fetch:
                    pipeline: #{upstream_pipeline}
                    stage: #{upstream_pipeline_stage}
                    job: distro
                    source: deploy
                - *install_language_plugin_darwin
                - exec:
                    working_directory: gauge-tests
                    command: /bin/sh
                    arguments:
                      - -c
                      - source $HOME/.jabba/jabba.sh && jabba use openjdk@1.10.0 && export PATH=$PATH:$GAUGE_ROOT/bin
                - *execute_fts
              artifacts: *build_artifacts                
