common:
  build_artifacts: &build_artifacts
    - build:
        source: gauge-tests/reports-#{language}/html-report/*
        destination: html-report
    - build:
        source: gauge-tests/reports-#{language}/xml-report/*
        destination: xml-report
    - build:
        source: gauge-tests/testLogs
        destination: test-logs
  common_materials: &common_materials
    gauge-tests:
      git: https://github.com/getgauge/gauge-tests.git
      destination: gauge-tests
    gauge:
      pipeline: Gauge-Build
      stage: windows
    html-report:
      pipeline: HTML_Report
      stage: package
    xml-report:
      pipeline: XML_Report
      stage: package
    package:
      pipeline: #{upstream_pipeline}
      stage: #{upstream_pipeline_stage}
pipelines:
  temp_java_ft:
    group: Gauge-Java
    parameters:
      language: java
      upstream_pipeline: Java-Build
      upstream_pipeline_stage: package
    materials: *common_materials
    environment_variables:
      enable_multithreading: true
      language: java
    stages:
      - specs:
          clean_workspace: true
          jobs:
            darwin:
              environment_variables:
                GAUGE_ROOT: gauge_bin
                GAUGE_HOME: gauge_bin
              resources:
                - FT
                - darwin
              tasks:
                - fetch:
                    pipeline: Gauge-Build
                    stage: windows
                    job: sign
                    source: test_installers/gauge-darwin.x86_64.zip
                    is_file: yes
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - mkdir -p $GAUGE_ROOT/bin && unzip -o gauge-darwin.x86_64.zip -d $GAUGE_ROOT/bin
                - exec:
                    command: /bin/sh
                    arguments:
                      - -c
                      - ($GAUGE_ROOT/bin/gauge uninstall java)
                - fetch:
                    pipeline: Java-Build
                    stage: package
                    job: distro
                    source: deploy
                - exec:
                    working_directory: deploy
                    command: /bin/sh
                    arguments:
                    - -c
                    - (version=$(ls gauge-java-*-darwin.x86_64.zip | sed "s/^gauge-java-\([^;]*\)-darwin.x86_64.zip/\1/"); $GAUGE_ROOT/bin/gauge install java -f gauge-java-$version-darwin.x86_64.zip)
                - exec:
                    command: /bin/sh
                    arguments:
                      - -c
                      - ($GAUGE_ROOT/bin/gauge uninstall html-report)
                - fetch:
                    pipeline: HTML_Report
                    stage: package
                    job: package
                    source: deploy
                - exec:
                    working_directory: deploy
                    command: /bin/sh
                    arguments:
                    - -c
                    - (version=$(ls html-report-*-darwin.x86_64.zip | sed "s/^html-report-\([^;]*\)-darwin.x86_64.zip/\1/"); $GAUGE_ROOT/bin/gauge install html-report -f html-report-$version-darwin.x86_64.zip)
                - exec:
                    command: /bin/sh
                    arguments:
                      - -c
                      - ($GAUGE_ROOT/bin/gauge uninstall xml-report)
                - fetch:
                    pipeline: XML_Report
                    stage: package
                    job: package
                    source: deploy
                - exec:
                    working_directory: deploy
                    command: /bin/sh
                    arguments:
                      - -c
                      - (version=$(ls xml-report-*-darwin.x86_64.zip | sed "s/^xml-report-\([^;]*\)-darwin.x86_64.zip/\1/"); $GAUGE_ROOT/bin/gauge install xml-report -f xml-report-$version-darwin.x86_64.zip)
                - exec:
                    working_directory: gauge-tests
                    command: /bin/sh
                    arguments:
                      - -c
                      - source $HOME/.jabba/jabba.sh && jabba use openjdk@1.10.0 && PATH=$PATH:$GAUGE_ROOT/bin mvn -q clean install -Denv=ci-java -Dtags="java"
              artifacts: *build_artifacts
