pipelines:
  Gradle-Build:
    group: Gauge-java-plugin
    materials:
      gradle-plugin:
        git: https://github.com/getgauge/gauge-gradle-plugin.git
        shallow_clone: true
    stages:
      - build:
          jobs:
            build:
              elastic_profile_id: centos-all
              tasks:
                - exec:
                    command: /bin/sh
                    arguments:
                      - -c
                      - ./gradlew clean build
              artifacts:
                - build:
                    source: build/distributions/gauge-gradle-plugin-*.zip
                    destination: artifacts
      - publish:
          jobs:
            publish:
              elastic_profile_id: centos-all
              tasks:
                - exec:
                      command: /bin/sh
                      arguments:
                        - -c
                        - ./gradlew publishPlugins -Pgradle.publish.key=AES:AJdgmUP4CuisU4NdxDIf3w==:VDEJi1LAUW16OnfhfOD9T0/M6IHUZPDBRX7RPOuYPLqpoa4WpWbGdIlUJDPKGgrk -Pgradle.publish.secret=AES:TOTMvIqfUNSOi5PUmorXFg==:ylj/BY3fQaDZuJiv1entFwf6SJn0U/S9DcvlWLyMxSah/iISOFYr1XaNyjLgpg1Y
  Gradle-Plugin-Nightly:
    group: Nightly
    materials:
      gradle-plugin:
        git: https://github.com/getgauge/gauge-gradle-plugin.git
        shallow_clone: true
    stages:
      - nightly:
          jobs:
            push_to_bintray:
              secure_variables:
                BINTRAY_USER: AES:khuxGHjHryC+c6inG1sOEw==:foru/1KYzJVuW7wWVgOnnA==
                BINTRAY_API_KEY: AES:rM1zuFCCwUrLgHEx4T7REA==:IxmC+vYVYToes++Tz+RiVotPMVtajbImds2LpwB3lbUqX92IR8fW1WwQ/jH2JrP8
              elastic_profile_id: centos-all
              tasks:
                - exec:
                      command: /bin/sh
                      arguments:
                        - -c
                        - ./gradlew clean bintrayUpload -Dbintray.user=#{BINTRAY_USER} -Dbintray.key=#{BINTRAY_API_KEY}