pipelines:
  Gradle-Build:
    group: Gauge-java-plugin
    materials:
      gradle-plugin:
        git: https://github.com/getgauge/gauge-gradle-plugin.git
        shallow_clone: true
    stages:
      - build:
          jobs:
            build:
              elastic_profile_id: centos-all
              tasks:
                - exec:
                    command: /bin/sh
                    arguments:
                      - -c
                      - ./gradlew clean build
              artifacts:
                - build:
                    source: build/distributions/gauge-gradle-plugin-*.zip
                    destination: artifacts
      - publish:
          jobs:
            publish:
              elastic_profile_id: centos-all
              - exec:
                    command: /bin/sh
                    arguments:
                      - -c
                      - ./gradlew publishPlugins -Pgradle.publish.key=AES:AJdgmUP4CuisU4NdxDIf3w==:VDEJi1LAUW16OnfhfOD9T0/M6IHUZPDBRX7RPOuYPLqpoa4WpWbGdIlUJDPKGgrk -Pgradle.publish.secret=AES:TOTMvIqfUNSOi5PUmorXFg==:ylj/BY3fQaDZuJiv1entFwf6SJn0U/S9DcvlWLyMxSah/iISOFYr1XaNyjLgpg1Y
