pipelines:
  HTML-Report-FT:
    group: Other_Plugins
    materials:
      gauge-tests:
        git: https://github.com/getgauge/gauge-tests.git
        destination: gauge-tests
      package:
        pipeline: Java-Build
        stage: package
      gauge:
        pipeline: Gauge-Build
        stage: windows
      html-report:
        pipeline: HTML_Report
        stage: package
      xml-report:
        pipeline: XML_Report
        stage: package
    environment_variables:
      enable_multithreading: true
      language: java
    stages:
      - specs:
          clean_workspace: true
          jobs:
            linux:
              environment_variables:
                GOPATH: /tmp
                GOBIN: /tmp/bin
                GAUGE_ROOT: /tmp
                GAUGE_PREFIX: /tmp
              elastic_profile_id: centos-all
              tasks:
                - fetch:
                    pipeline: Gauge-Build
                    stage: windows
                    job: sign
                    source: test_installers/gauge-linux.x86_64.zip
                    is_file: yes
                - exec:
                    command: /bin/sh
                    arguments:
                      - -c
                      - mkdir -p $GAUGE_ROOT/bin && unzip -o gauge-linux.x86_64.zip -d $GAUGE_ROOT/bin
                - fetch:
                    pipeline:  Java-Build
                    stage: package
                    job: distro
                    source: deploy
                - exec:
                    working_directory: deploy
                    command: /bin/sh
                    arguments:
                      - -c
                      - (version=$(ls gauge-java-*-linux.x86_64.zip | sed "s/^gauge-java-\([^;]*\)-linux.x86_64.zip/\1/"); $GAUGE_PREFIX/bin/gauge install java -f gauge-java-$version-linux.x86_64.zip)
                - fetch:
                    pipeline: XML_Report
                    stage: package
                    job: package
                    source: deploy
                - exec:
                    working_directory: deploy
                    command: /bin/sh
                    arguments:
                      - -c
                      - (version=$(ls xml-report-*-linux.x86_64.zip | sed "s/^xml-report-\([^;]*\)-linux.x86_64.zip/\1/"); $GAUGE_PREFIX/bin/gauge install xml-report -f xml-report-$version-linux.x86_64.zip)
                - fetch:
                    pipeline: HTML_Report
                    stage: package
                    job: package
                    source: deploy
                - exec:
                    working_directory: deploy
                    command: /bin/sh
                    arguments:
                      - -c
                      - (version=$(ls html-report-*-linux.x86_64.zip | sed "s/^html-report-\([^;]*\)-linux.x86_64.zip/\1/"); $GAUGE_PREFIX/bin/gauge install html-report -f html-report-$version-linux.x86_64.zip)
                - exec:
                    working_directory: gauge-tests
                    command: /bin/sh
                    arguments:
                      - -c
                      - PATH=/tmp/bin:$PATH mvn -q clean install -Denv=ci-java -Dtags="html-report" -DinParallel=true -Dnodes=2
              artifacts:
                - build:
                    source: gauge-tests/reports-java/html-report/*
                    destination: html-report
                - build:
                    source: gauge-tests/reports-java/xml-report/*
                    destination: xml-report
                - build:
                    source: gauge-tests/testLogs
                    destination: test-logs
            windows:
              environment_variables:
                GOPATH: C:/gauge/
                GOBIN: C:/gauge/bin
                GAUGE_ROOT: C:/gauge_root
                GAUGE_HOME: C:/gauge-plugins
              elastic_profile_id: windows-all
              tasks:
                - fetch:
                    pipeline: Gauge-Build
                    stage: windows
                    job: sign
                    source: test_installers/gauge-windows.x86_64.zip
                    is_file: yes
                - exec:
                    command: cmd
                    arguments:
                      - /c
                      - "unzip -o gauge-windows.x86_64.zip -d %GAUGE_ROOT%"
                - fetch:
                    pipeline: Java-Build
                    stage: package
                    job: distro
                    source: deploy
                - exec:
                    working_directory: deploy
                    command: cmd
                    arguments:
                      -  /c
                      - "for %f in (gauge-java-*-windows.x86_64.zip) do %GAUGE_ROOT%/gauge install java -f %f"
                - fetch:
                    pipeline: HTML_Report
                    stage: package
                    job: package
                    source: deploy
                - exec:
                    working_directory: deploy
                    command: cmd
                    arguments:
                      - /c
                      - "for %f in (html-report-*-windows.x86_64.zip) do %GAUGE_ROOT%/gauge install html-report -f %f"
                - fetch:
                    pipeline: XML_Report
                    stage: package
                    job: package
                    source: deploy
                - exec:
                    command: cmd
                    arguments:
                      - /c
                      - "for %f in (xml-report-*-windows.x86_64.zip) do %GAUGE_ROOT%/gauge install xml-report -f %f"
                - exec:
                    working_directory: gauge-tests
                    command: cmd
                    arguments:
                      - /c
                      - path %GAUGE_ROOT%;%PATH% & gauge version & mvn clean install -q -Denv=ci-java -Dtags="html-report" -DinParallel=true -Dnodes=2
              artifacts:
                - build:
                    source: gauge-tests/reports-java/html-report/*
                    destination: html-report
                - build:
                    source: gauge-tests/reports-java/xml-report/*
                    destination: xml-report
                - build:
                    source: gauge-tests/testLogs
                    destination: test-logs