pipelines:
  check-all-readme-files:
    group: Misc
    materials:
      gauge_docs:
        pipeline: docs_gauge_org
        stage: deploy
      gauge_website:
        pipeline: gauge.org
        stage: deploy-live
    timer:
      spec: "0 0 12 ? * SUN *"
    stages:
      - getgauge_repo:
          clean_workspace: true
          jobs:
            check:
              resources:
                - darwin
              tasks:
                - exec:
                    command: npm
                    arguments:
                      - install
                      - -g
                      - --prefix
                      - /tmp
                      - markdown-link-check
                - exec:
                    command: /bin/sh
                    arguments:
                      - -c
                      - curl -s https://api.github.com/orgs/getgauge/repos?access_token=$GITHUB_ACCESS_TOKEN | jq '.[] | select(.["archived"] == false) | .clone_url' | xargs -L1 git clone --depth=1
                - exec:
                    command: /bin/sh
                    arguments:
                      - -c
                      - curl -s https://api.github.com/orgs/getgauge-examples/repos?access_token=$GITHUB_ACCESS_TOKEN | jq '.[] | select(.["archived"] == false) | .clone_url'| xargs -L1 git clone --depth=1
                - exec:
                    command: /bin/sh
                    arguments:
                      - -c
                      - curl -s https://api.github.com/orgs/getgauge-contrib/repos?access_token=$GITHUB_ACCESS_TOKEN | jq '.[] | select(.["archived"] == false) | .clone_url' | xargs -L1 git clone --depth=1
                - exec:
                    command: /bin/sh
                    arguments:
                      - -c
                      - echo "{\"ignorePatterns\":[{\"pattern\":\"^http://localhost\"}, {\"pattern\":\"^mailto\"}, {\"pattern\":\"https://maven-badges.herokuapp.com/maven-central/com.thoughtworks.gauge/gauge-java\"}]}" > config.json
                - exec:
                    command: /bin/sh
                    arguments:
                      - -c
                      - find . -iname \*.md -maxdepth 2 -mindepth 2 | xargs -L1 /tmp/bin/markdown-link-check -q -c config.json
  Common-New:
    group: Misc
    materials:
      common:
        git: https://github.com/getgauge/common.git
    stages:
      - test:
          jobs:
            linux:
              elastic_profile_id: centos-all
              environment_variables:
                GOPATH : /tmp
              tasks:
                - exec:
                    command: /bin/sh
                    arguments:
                      - -c
                      - rm -rf $GOPATH/src
                - exec:
                    command: go
                    arguments:
                      - get
                      - -d
                      - -u
                      - -t
                      - github.com/getgauge/common
                - exec:
                    command: go
                    arguments:
                      - test
                      - -v
                      - github.com/getgauge/common