pipelines:
  Spectacle-New:
    group: Other_Plugins
    materials:
      spectacle:
        git : https://github.com/getgauge/spectacle
    environment_variables:
      GOPATH : /tmp
      GOBIN : /tmp/bin
    secure_variables:
      GITHUB_TOKEN : AES:I3dqwn71FdbHJuV9dq8p1g==:F+KgcT2E9/sji7moKR3yA+PRvQkjeg7/TJJlncRKmYQ+tQOHn78jiYY3u6pTkswv
    stages:
      - build:
          jobs:
            linux:
              elastic_profile_id: centos-all
              tasks:
                - exec:
                    command: /bin/sh
                    arguments:
                      - -c
                      - go get -d -u -t -v github.com/getgauge/spectacle
                - exec:
                    command: /bin/sh
                    arguments:
                      - -c
                      - go test ./...
                - exec:
                    command: /bin/sh
                    arguments:
                      - -c
                      - go run build/make.go
            windows:
              elastic_profile_id: windows-all
              environment_variables:
                GOPATH : c:/gauge
                GOBIN : c:gauge/bin
              tasks:
                - exec:
                    command: go
                    arguments:
                      - get
                      - -d
                      - -u
                      - -t
                      - -v
                      - github.com/getgauge/spectacle
                - exec:
                    command: go
                    arguments:
                      - test
                      - ./...
                - exec:
                    command: go
                    arguments:
                      - run
                      - build/make.go
      - package:
          jobs:
            package:
              elastic_profile_id: centos-all
              tasks:
                - exec:
                    command: /bin/sh
                    arguments:
                      - -c
                      - go get -d -u -t -v github.com/getgauge/spectacle
                - exec:
                    command: /bin/sh
                    arguments:
                      - -c
                      - go run build/make.go --all-platforms
                - exec:
                    command: /bin/sh
                    arguments:
                      - -c
                      - go run build/make.go --all-platforms --distro
              artifacts:
                - build:
                    source: bin/distros
      - release:
          approval: manual
          jobs:
            elastic_profile_id: centos-all
            environment_variables:
              repoName: spectacle
            secure_variables:
              GITHUB_SSH_PRIVATE_KEY: AES:dnN1D2l9lFwY5KfkcluoaQ==:l9ykvQwSX6uaXO8VeVoSpyDdRwNZF2sAvJx0o9EiEUV0EXTS0Z2Tux0yr2I+sM9DhFb5AqebXJKoGJdY/p/cBLx5qOOQS6ybI214I5oe78g1sVRPNuVfv9KNmAYq8HU3ygMocMRuIbNeFlWBWjfcPuBwD2xXgbUmTv8GuFmfkAzzWbH0ZMmy3cTBT9bGbhle6MRrppRcybDMx/jTYz5REBJE4MlfN+ymIh42L3QAPPwVF29bynefeNn5r7SptyNAMjCfoapKrYNyWdKGMP2DMsC/uGSOnnWvRKA5gDgASoPfsFf4axtDWnfO5N4pKasZOHiAiAJlTVaDR8iLTBRxPoW0wIRoe3us6EY5n7IegtN4EJX3e8YRJY5o7/Opwn5Fc8Wt88nvap/Mm2MKJrxvYh26HgFWJridGaXv6Pi8hBRVcGHdIFv1DKNxKI3xI4WAmqn0Ynv3ZTjmZE+B92J/mcsaugj0mHJQZXSIHgCMLTENudGZO9EVhcsRv945XnnDxnL63JnZmKBVD8XUm0ST/VM57TVz2i+wk6MXkkX6imW2OT1vNvgYXk88HCby6KhONBst0yxJFoMzI8cIxIe1CzkzsUYIqpCt25ofNlPEJm3DRB9ESW2p9RNcbQx3VvRVAVFLMFFlCH9ruXeCmz2O1q+gBTayEwLFOh+TD+m6nBC0H4vlztDCsJZHF4j12Lbptx1jGEuDE1o3kRHLs/79owBCxbJB0rXP8mGzk9F3rAD9nXeTO5KPmcfn9CnFH+N+IOYbfTm8U3td6cW5Psb3hx+ixpyDe9DulDIiUUQLWc7cEa/ox6JfOPVvuiiyyftyw8JZkMcG5/UZBHvjcg5n6b3Sxpu7AMUQcMXQcNkYGzd+fz8PQfaLagQtIv5yYGYC8qtRWRWKToyuZpsJDfy47JkPiaBejVeMaFVL731nV/GHAY1e9YumJ3EunH5RnmPkyNjX/V5ZphvenYgfyARBsmDdxBT1xDxh3NHoj0hM7cpajsnjQ5AsLdud5mHNBBFZOhSlOa+Z1MkqQQ+VM5rassiAJXilAlO9gVd9IoeUVmBgsWVAMcxEPv7c2Bg517yaajSIpLuVoPHaWE2BSXox0Q+PfRdWE8weUymD+6qAQnaWMdD7SfJR+zv5EK7MdEna/gWAPYFWjwBaCDqpCgvpQOm056GkLjRKbINGQOz1pRPCW+0isOSJuCUujhdPtDs9rUeVnltZnRc9PpFRRl9+hHMNO+PDfpxhx5BESJQMV6uRJdtUCkEmPaBdJ2O9CZlHVpnfT79AxA22WDok7WrrG3b6t7p3nMWTUcbNdU3rSEDGhajndQXCnzTnlt6WHGI4yeyDw4nkF+EVzhbmPhiuUUYlGEUDmV0kuqEUwDoIv+A/bewNfL8Vc7JitY73Q/nYP7sle9EBoaiVbo3PsxIJ10VVdupit73p4UJnl7NUwq9Im8bzuDO1BqpnfWWP5HeOotSlo7d3kTB8CuRHYKNXmXchg02/njU3ogLoCXOns8MQrsqwYWcY8ob2kCXiglSQ+3gt8fBZtsU6jBsWJX+SiB2XGdkvCL/A1FdvE5wpfcrm1B5YRHZs4okPuj/xhRMaPsvhQYBwb/dgjcNzMfLR+7q/hO3+na81VNsRLSbtyeTX6tLMlE817jgvB3mkGhus476V2bV74VvjC/uJLNtSubwEkM6t6+qL6H2mu0qSWjDbEVgZsxaEACrINgYiPF4GEsF1Oa/FFssVys/xuAS7adpqXV0znpqoVPTbnhOPJJ72fPulagKe6D5qMQEmiMYBIEnxmJZDgRndqsz2Hu9viLwX15VZ5CywdGl2+sRkYGmhlUIRLu/RaUfTGUX6f4NnlXT1KIbV/istLrTYkM1UzYzk9WyJ+25dAupT/9pmmbyHJIFbUVUCSOk0O0lVDW8KFIjPsEzBqoOiaGtiQ2HjmPq7FWE081/gMFSs3MVMFgIDX5eLJsl2i5jSAsy6EvXw2E+PI8E/r6pfYtbaX9RC5zzKZanQ9AWa42fbAR3AFMxwFVB2OBvYeMiCmUTo2ao+Ee0bNlxppAAFtcMI2mYa5JZlsCdyz5vzZpFyFipIuXzH9XCRFC5EsfT4oPC8Hay9H/L7zaRwAnOkh7/sSpSuUobA7TuF3BsCGaJbAyj8t3/DkpBykNNnk6apnHoQHr24q22+YWHCBvQMlcfgsj2+Ch0KrQ/jXdClmsuVyfHutteFdWGoBoemfJrxqdWhryN6a9gBSNjH0l0PVXM9WbXABZJTHUaeCLweaHNtyYn6NBXjS/GOIqQNVW/bv3OV5HbR0y6JR9FoLLl6E2hWV7tm6jO+3jvVOH0ChNbj4rjKYZCY9yQqJgsnL0dWwchD1RgNMcZ0UX8/CgvIVcrBdOjoPsmzAQ8wDuIEYjZ/G47lgQWx4VBik2v0z/Akl9MGEvXb1V91DrGff43ELOAZtj+ZpR8ZtPSOA9QPHSqY9KhNRXwWmTbETyRN4RLdHpUSEbZ3aM+5Wt7pOjjR72n2wDClbjdm5yCwbolslm/WZgAdebciORp5vfEdaolU4bkLIunhBpx7kjRz03eMy/zIaRtUAuukSFG07Ccp1yKewkH/sUTBcxFAavwnHiEaSIAoAOPhnwi6pKtM6gnf/CQvvmYx9JOA/XiMM2YNxTP9lpWP++qkCSwUUQRtMI5E+xNJUOeTbPXCotm01GfVZc24TB6gXAR3Iza1l3V1ekKTNG2Hgw1GAOniuzpr0Y3T0MoQ4CnP/1TUYKCnlOG50Qm8mErxi8Jvs1oYXpcrZDCjVG+vTKepWC5K3GffulldwFqV5O/M/U/G/fks4F89/GGggvb8G7f3lTD8wVr46R4AhwUhhUqkYAsJPum+hN6efBEVjSic1An3afZ5L2RM48qLQW4QH6UkLpUyHEHt4N5urG2x+kwCsTTOGHh1YBhFF2d4nvX/BNXZmxo29JmIHuQYXJy1fKmEhIJevgmpIXY8Ax9C/0svNfh7yNWzyDo2V1tz0PNDUyGYGUSvHBXHB/aDozDJu/kr1t/Bw9fHZAIAb9QmxOIoDStl9/eFKEToA8E5xYfxq8qh62EiVE4FTZyHf0qKSZGfitOcL8UHKxW+VxJMd6ntJOjEwr/hR4W+3pjg8tuC3sIo59YalPNgOxyA7uQVBKA27KJ6gK90B51h4g1/L/YI7Mv7g+lSYfQuNVNnloWwtDMS0FNsQZuJ9ufFqmV9DZbA90icWe034+QsKor+IcF81hMSQ2xvjGf9WUGtbHEXMB12GAK4T3UM8ssWsHDSQQn2usOFROUtEcpd/Sv2xr9h41w4SRcARopbdCGJkVe3IXI5sPBJYbdG9EcUnoHcjHoCRiO/Ppq9MHsiMvBnLjnxXLvLCMzsDay5kO34wcFrfmCTFuqFSPuEAUtVDyekUfn/Y9qt0iXNGp8ILLVrPobvINQOvfE3BvQ7ypek0JVC5La+30uZfpEC5H7+GG0aKgYb7esQMFS/DA8uLN8uJe3YDfxyJgPMhsEEF0hpDwokuejPVfvgfqtrxXfuhpcQxYCDPs+AdjEZJYAouM1vApJMjUIHl8A6cBR2WsZsa9R4lduDLmFknqnlsRbqQf4fy/gRqJpdug5ZBpPpcHC3XC552rdP2DKyu1W/PH8mNVEYk8aPdqp0jDlB1yimZVQ9zcQspXHYHf+x1AaBsL9f8IpG6xNQyF0n5mScxz5zPMWf5YSHxUm9lbM0FS8Mv/OGbBq4EaCpUe87Flly47lbyfRuvcFPms0S7IDmct8CgyqkFvE/UQxMv1rtKtp8ssUNMhoi759bVxuZGWcz2BrgjMOX5YSoo/PhAOoQ4UkBRqS2ZeSHR1GCvCTr7udTUlcaOTApx4heQlUQrsUQoAsi9yNPH40U0HTsEFAC7ZObK4vTQx/ehaswhpqxBlPxf1nCmUxUYVfnpLdFKKYT+nIfXl0DnmZLF8yUfJYv91eH/iOYEAtZKqZD5+hXWg9FWpzS3UWTA3eiN7mWWV/RhyQG4PdU2XSqaDmjiFiGoMudwaM68p6QrsYZZtPCoPUFUjDWKWFQGwZQntwxlLw4oe/clRHzvsS+IztsKLgKu0TsVyGrmcLdH0tOQjm1UC7V3WvLeRR8EsqmxNj5dxXcB2qc5uWyMJIgCTqeUIaocVVSJsf3exF7rvypu41OcAZsyo6J6y/mThSl2AqcRjRhVyqObyJikXG8ZxyhE3Upt/qAtk/wMav1b7j6381pfdxXP+Vs8vPDCJY1Qp5EJ6mMryes9V9g6Ds8eo+hdmF6oelIW2DXlI7RsQe/Ts8ruQ5n524gKkXSOtA2j6F25uXF8DT8elyD2SadTT6gu27uCsZDfbo5Pc7ATNmdMdzSGnph8Mj2QghkfbU7LEHinCsatQGXNf6I5ngj2YWj682hxszEvXGO
            tasks:
              - exec:
                  command: rm
                  arguments:
                    - -rf
                    - distros
              - fetch:
                  pipeline: Spectacle-New
                  stage: package
                  job: package
                  source: distros
              - exec:
                  working_directory: distros
                  command: /bin/sh
                  arguments:
                    - -c
                    - (curl -sSfL https://github.com/getgauge/gauge/raw/master/build/github_release.sh | sh)
