pipelines:
  Taiko-Benchmark:
    group: Gauge-JS
    materials:
      taiko:
        git: https://github.com/getgauge/taiko-benchmark.git
    secure_variables:
      GITHUB_EMAIL: AES:+LFTS7BtnVEFaBRMNOGOJw==:gP17lhYFS8vZRBN+BnE0rxH2onIm/XAzAPmgY9OKNAw=
      GITHUB_SSH_PRIVATE_KEY: AES:pHi8Eruj+l0XApRND76kEw==:Sl8X0SJKfEsi4b2jFw1frE+YC1hBUWKrwiiZlK70BKkMtyaK8p7uHxa2GZ2FX3x8u8RXYp+pZOoIVSIKNSLN/Gv6WTfR6ME/XiL2KDVKpR6AJJoi19y0Ywg4i9fUu0QnIBD0k1P5my61DSKTPTEQg2McjmP4BoQjIoz1oez9N71Lrd8aYQTwVkbkNG0bJ5k2oxYnvQZ8uJsi1geUt6GkhFnaSa5XQXfDXoZ/xBy6gwfzCgciPbBiJhWDyOG/Ov6N7CFtYkKjGXNUU1yoE5vJfZFWQ2j74JQnNOYySvxYoaliB5nJd6WYr3gXpoYCLCs1isUAog+c1ZANk6sIUzQSxgRcliXbDsQNqEypj6bj0ZXNLpAOtEA7yctrLt/pnB1U+vglz5QNDcP/P5sABAkz9jvInP8KXxwjg63CQHpdE5bSJEJfDiuvxK252747KSGv7Xp8y9m3uHTcwbrfQTB6qsCDhIXq+8mjLOuJ/VXRY7P1yjyNl2BH3ZcrMT+3mi36FWWMb7GrV7XhtktlUjttCvGzvnLSLGKUK228V0F7YiBHX7gBQLENsgGYkE/a5U9NRThAITIACW6IHEit0ozPTOcnYqXDHmHRwUavD/cOe4vznu9HViicyMWW/G31NZwcskbn7kKNHragcA/eo6ATMqcwj0Dx3l1UMLQMTPGS/qcMsRznqUaOSTMfGMu3YDF7bszGf8ExEzvAjvhhWG2pdcA2OL81/jvpUjdlMjoT4UShxZMotU5CkUtTmD0btZG9+XSh5X0QjF3sHAd6UsYowfeCQhD4rGS2xt1orHxU360ziwp0lLTpuXZr78iKE1JELa+Toyv5Axg2GFrCMvfkYBYM5xKtKW2kFX0RRZkEXRN00aA9IilpyLMNFBwXHmlF+EfHzoz9SKjwefbngR3JyPh/ewvPT+tgtkpPLSIUkJWOegfjZRl9gxhcy4yMiTnnUZkS/Nj3/yzYaaEWN/lRMYUTLcBvvJjm23EEvVdhEAGG82V9/P8pwm1CdVyzBgs4+HZ2MO49iu7VGvVeqPsgKApIiX+rGaMyVjFN38apt2TyqqBiE63uG53simtOZTOTMeZ3AYGuKeyDaDvSY18Yu2fFiqcEMsHB3qSCD58uUCHy1VuDGLZ9kTqU8fspce8RlbqDIzSTcY11fbQbrtHzbMwxYflD0wJac179qxLiDj+EK3ZUsZhkNwe+qN8hTfD1I2ZCDkpvpNUYWtboB70JTRCUVrr+tlpq5m2JR9pgXV0Hts8+l5GbWCNWPo/GzB+ZWFxVoT4XdY+ixPQ+tgdJqDfMwPWZ/KB9/CyCUV5T1pbxG060RPV++c5p6lwDwwdFizOzQZ9UYpYzUcAww/e2DnT9WmdequIlYc7Bl9+sHYV1Bp+atcCja7iQq6ybpwb3fZeK6TIfycZA5nEWNDM/5tuNhmejDFCQPdeEPLBnloAmEScbfoGlNYz0LhpaVQP8qwkos7Uy4Y5MDXtC7ow/Xnj728c57Ko0SKWKXnncaTyByZdTJtCQMTMe7ilT5CMHUSIT5RGsGwtl/sBfGq0/WM2tzwvo/TAVn4KhmxdTTLPFNQkwfRxkL/1s176gaosJ40HIWx4mYILe6zdYa1ULXNqmyvZg2de5q/V0LKe3te+YP1NuHvZiz+zO1AZbvkU3Ge3Q8nrcTR12eB9A0x3TiNB0Ro7YyH9f6OAB00/IC6i8g1BY3mdwGeJktQNOzAYDirz4fvNWih5zZdfOqH/xYaSsv9PyctwsXSi8cvK7oYJjjx7HeXyiuRQZiGneE4V5jyAz77A13000cVARorM1SlvK3al3E55MmLsNS6llVlBIjDoewHSzspdtaWCm84p/O7j8Fsz7sp+kPeyqhXuAZP8fjEXqBaauwFGQYIc7D0eTdSq2Fvx4tCw+MEzkNNkk2hwCgcB33nQNvwCjTTSNMgwW/KSszsVtq35h1RkU6oINzHHxr5uBdyjcYaoS7DIJegD2CzBaQSc1JHkSQlL43Uu11X6dItDM+r8zgRX6j6DxC1Jeu4kl/5AvOqa+x5+NQltn1UbCsT/xQcUX3RFIM6hTFNE3gl8vwEEXaX5hA2rSuqyRDPni0x2zXwHall/tA9GVBvX5UzDd9FQjOsoqkmv+B0m29VGuEK2kd8wrpVIlc3dc/iaxRt8xci2LfG6onO1bXb4mHo1FNZUrJ1gH27hEVa2Pm4mCD42lXMaY8yRuzrJ6larSzlVsKM4B7E9Eln6bocuvifCM3OwKDmda/kTf0YF0xU420onOFlAKb1VSO+at9S4gLqEy8e1H07l+AOERhk+bbUC8uytB/dzwbLbDhfXj7eWL8GtuIexNwKd2te3Fy2vxmHeer8zckag3qOyzytMrVf1+2SSgNsCxy5Ib05V7MdOQxY3oYXraEvceMnQu2ce/vqZFdIJuJHkbTIrPzwqeYLfwTc2GYTJT+3Q6AOPqnQM1LsX0cYxgS8ACpD8DMfUs7uEtP2o857gXXUQRgihcNM+9vpS/Hzt4eEOEQmkaPvFTFo+6AaJd/AIuWJxNmYU2zxC73honsjQdiPGdIdtJmqD2xdpY/Kj01kiJmM1mC3D7e0WVD95f/Ya8ZzNbuae3VEKGMTy/MhSODMRuPikvlHYpXI9+9/jevapF7XeyX73PiMpKA+DqoTUGGQ0lvpa5jIxYQ2yA5bTJGtLCse1SCEymLdyNvh2JZnrByisblfuk+6U5EbnUSc9rMiD0ZPNMbLjqRNjbr2JtgHEKDVfqlZixPHZCKwW1Xqy1Vy5q4n/T49v2KbFNA7Bj2uBZ58yYXlSNxlxvreVFGZYqOh77Jvhc++DKf6o50ccgBzjNZ1+jYfxsC0mNTjtwfWlkC13nm0KOonHhI72xWVbQm1SEbI64ZcF3D+cNiLWPEFPC+HA8ThOwCMnF2o6xrquQKAK3yvSXQv2O2g8iQCbSxpMs553Hrgq0/+qFxwlBZ5am7MkgOTu82VLZs2wyfVm+IiCJooVUjL5ObROEkx0qSC//hDeJZHl656zbG2nVbIzg7ToCWWvfJn48hnyouyyFmIDonUEOfNeMmufgjwYCWxIKjnHOApAK050pFCda2y/4lbIpnFNpct7u1ae+aufdgVUD7dy32w0b+I6c1Qgdj/VZWhMlEe84gi5t8UoK5Df1Xfz2/CxweoXNlPxTr/tJJ7nigBKNdEYWKusgztCN16xmbALqCCXYazApchz4zfFizZGdOlrx9oOUJGXNdb2T4VTWox5GA91BM7haKWBkeR/VqhFSyh54vGRVBv+CD5W8Bx4GBqHYvif9eH27UCmepqFWbMoi3G9xooQ7D2Ob32xRoQGRTplvpLPYfec4MzQNWyZdPp7YsQlzhb5rOR9tebEtTzbGzhgKry7uRGTuV0colKurWVN0RoyAci23yw6PO2DrojX3b9Odmtsm+EM6JO1E/pv1XpUWwpgN5rayszn6oBpcwOA+9/tcqIIqg7YJQ67pebDnHhv0hkvwZYqo3kLvbos5ZbTfZtn+Qxc4xmH6UAFCK605/TS4zkBgAPOduOQ0/mXoR/FL34POzGMRHhpwX5oJiuz2BvMGdgqqpKx87g07WVdaz9dReta8vaPy8HZPARnRq3hH4+lgnPXkaOQuvYJEQjen7ws+LV2lrBKRFWREf+jEsY+gFBO5bbcznr4N5Ed73SoZA77yMzOSbDlhvSD3ecfwHrZkJKcgrMDN+QMIsCw6HxNicNuog9A75P1/1GC7BypE3GAo2hH5uEcJrsvKWKoSYSlohHsqLtyUt4P4g+Bz0/m9zFvznAZOIWYVjuCW2QtCIOtQqBVuxjR0EjqybiAaGBxZw+U5eV6vNRV7BNhbF9yJk1IBClEYHp1jABMbWopSAgSNTmnJuomDF4S5UEqtDvJzuGeO1injmvkwYlX5lhwknGn4UjRoYmFMRSFANpIlqU4zO4/IftlaOn/5y4dG4RApymmW5Upg+V3Ut2NESQQXQl2NzGOiZRIXecWPj3n26CNIWWIengQUuA5ZZMNVnpitDH8tkrx2FXRaqq7ywo6Dfq3FxG7SQwnM9lWaFVQ7lzZpWs9Rmsk/6l9or6tgghoKtpMknqem0q1n0EoBgVm8fpDELCUu9MdJCvo4HTGN98ohA/77SbgsvndQDDaiMfsUAtCuZNp92eAVyEiJVR5TmTxlLkBFCo8eMKFX3SBiSti1QEPTZhmPlg/WUvs4wbL73Io39BsfFIaVjUzNomhOMGVoen/FNvHuQwMsZiFr67AoJhffMdl27KMFpkl/GrlxnwlO1XPgBP30QeLuGYkjZuBE+gEc7KS8L9lzurhrwR6lbzkjkp9gI4qaRqQGjnJVPSpcEvancDKgW/m0AmQTXSCHlaB/aA3wlGlr8Bx5oTlvOMMCB+XnhOmNmX8k7/CT
    stages:
      - benchmark:
          clean_workspace: true
          jobs:
            linux-benchmark:
              elastic_profile_id: ubuntu-node
              tasks:
                - exec:
                    command: npm
                    arguments:
                      - install
                - exec:
                    command: npm
                    arguments:
                      - test
                - exec:
                    command: /bin/sh
                    arguments:
                      - -c
                      - (git add ./reports)
                - exec:
                    command: /bin/sh
                    arguments:
                      - -c
                      - (git commit --author="$GITHUB_EMAIL" -m "Adding benchmark result for linux platform")
                - exec:
                    command: /bin/sh
                    arguments:
                      - -c
                      - (echo -e "$GITHUB_SSH_PRIVATE_KEY" | ssh-add - ; git push origin master)
            osx-benchmark:
              resources:
                - darwin
                - FT
              tasks:
                - exec:
                    command: npm
                    arguments:
                      - install
                - exec:
                    command: npm
                    arguments:
                      - test
                - exec:
                    command: /bin/sh
                    arguments:
                      - -c
                      - (git add ./reports)
                - exec:
                    command: /bin/sh
                    arguments:
                      - -c
                      - (git commit --author="$GITHUB_EMAIL" -m "Adding benchmark result for darwin platform")
                - exec:
                    command: /bin/sh
                    arguments:
                      - -c
                      - (echo -e "$GITHUB_SSH_PRIVATE_KEY" | ssh-add - ; git push origin master)
            windows-benchmark:
              elastic_profile_id: windows-all
              tasks:
                - exec:
                    command: npm
                    arguments:
                      - install
                - exec:
                    command: npm
                    arguments:
                      - test
                - exec:
                    command: /bin/sh
                    arguments:
                      - -c
                      - (git add ./reports)
                - exec:
                    command: /bin/sh
                    arguments:
                      - -c
                      - (git commit --author="$GITHUB_EMAIL"  -m "Adding benchmark result for windows platform")
                - exec:
                    command: /bin/sh
                    arguments:
                      - -c
                      - (echo -e "$GITHUB_SSH_PRIVATE_KEY" | ssh-add - ; git push origin master)
