pipelines:
  Taiko:
    group: Gauge-JS
    materials:
      taiko:
        git: https://github.com/getgauge/taiko.git
    stages:
      - unit-test:
          jobs:
            test:
              elastic_profile_id: ubuntu-node
              tasks:
                - exec:
                    command: npm
                    arguments:
                      - install
                - exec:
                    command: npm
                    arguments:
                      - test
      - functional-tests:
          jobs:
            linux-specs:
              elastic_profile_id: ubuntu-node
              tasks:
                - exec:
                    command: npm
                    arguments:
                      - install
                - exec:
                    command: npm
                    arguments:
                      - run 
                      - test-functional
              artifacts:
                - build:
                    source: test/functional-tests/reports/html-report
                    destination: reports

            windows-specs:
              elastic_profile_id: windows-all
              tasks:
                - exec:
                    command: npm
                    arguments:
                      - install
                - exec:
                    command: npm
                    arguments:
                      - run 
                      - test-functional
              artifacts:
                - build:
                    source: test/functional-tests/reports/html-report
                    destination: reports
      - publish:
          approval: manual
          jobs:
            publish:
              elastic_profile_id: ubuntu-node
              secure_variables:
                NPM_TOKEN: AES:smCSdWEkiHlJgx9yY+uCQQ==:oJgEJ1fMOzrQ7Ot62KcOj8dqPFKApy8X2E19uy793RzIl1NEi3JTTbHGn2CyH6ew
              tasks:
                - exec:
                    command: npm
                    arguments:
                      - install
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}'>~/.npmrc && npm publish
            github:
              elastic_profile_id: centos-all
              environment_variables:
                GOPATH: /tmp
                repoName: taiko
                uploadArtifact: no
              secure_variables:
                GITHUB_TOKEN: AES:5M8sxVr62XcjB5nQXkByQA==:2htgkabgxfyPGtwzwUmKI8Aa4V3gg/kA9hSpMw+Z+wTScfcWrHHYH9mEMQbZ21IP
              tasks:
                - exec:
                    command: build/github_release.sh
