common:
  - linux_unittest_tasks: &linux_unittest_tasks
    - exec:
        command: /bin/sh
        arguments:
          - -c
          - . ~/.profile && nvm use ${NODE_VERSION} && npm install && npm test && npm run examples
  - windows_unittest_tasks: &windows_unittest_tasks
    - exec:
        command: echo
        arguments:
          - ${NODE_VERSION}
    - exec:
        command: nvm
        arguments:
          - install
          - ${NODE_VERSION}
    - exec:
        command: nvm
        arguments:
          - use
          - ${NODE_VERSION}
    - exec:
        command: npm
        arguments:
          - install
    - exec:
        command: npm
        arguments:
          - test
  - windows_examples_tasks: &windows_examples_tasks
    - exec:
        command: nvm
        arguments:
          - install
          - ${NODE_VERSION}
    - exec:
        command: nvm
        arguments:
          - use
          - ${NODE_VERSION}
    - exec:
        command: npm
        arguments:
          - install
    - exec:
        command: npm
        arguments:
          - run
          - examples
  - headless_functionaltest_tasks-linux: &headless_functionaltest_tasks-linux
    - exec:
        command: /bin/sh
        arguments:
          - -c
          - . ~/.profile && nvm use ${NODE_VERSION} && npm install && npm run test-functional
  - headless_functionaltest_tasks_windows: &headless_functionaltest_tasks_windows
    - exec:
        command: nvm
        arguments:
          - list
    - exec:
        command: nvm
        arguments:
          - install
          - ${NODE_VERSION}
    - exec:
        command: nvm
        arguments:
          - use
          - ${NODE_VERSION}
    - exec:
        command: npm
        arguments:
          - install
    - exec:
        command: npm
        arguments:
          - run
          - test-functional


pipelines:
  Taiko:
    group: Gauge-JS
    materials:
      taiko:
        git: https://github.com/getgauge/taiko.git
    stages:
      - unit-test:
          jobs:
            linux-node8:
              environment_variables:
                NODE_VERSION: 8
              elastic_profile_id: ubuntu-node
              tasks:
               - *linux_unittest_tasks
            linux-node10:
              environment_variables:
                NODE_VERSION: 10
              elastic_profile_id: ubuntu-node
              tasks:
               - *linux_unittest_tasks
            linux-node12:
              environment_variables:
                NODE_VERSION: 12
              elastic_profile_id: ubuntu-node
              tasks:
               - *linux_unittest_tasks
            windows-node8:
              environment_variables:
                NODE_VERSION: 8
              elastic_profile_id: windows-all
              tasks:
                - *windows_unittest_tasks
            windows-node10:
              environment_variables:
                NODE_VERSION: 10
              elastic_profile_id: windows-all
              tasks:
                - *windows_unittest_tasks
            windows-node12:
              environment_variables:
                NODE_VERSION: 12
              elastic_profile_id: windows-all
              tasks:
                - *windows_unittest_tasks
      - taiko-examples:
          jobs:
            windows-node8:
              environment_variables:
                NODE_VERSION: 8
              elastic_profile_id: windows-all
              tasks:
                - *windows_examples_tasks
            windows-node10:
              environment_variables:
                NODE_VERSION: 10
              elastic_profile_id: windows-all
              tasks:
                - *windows_examples_tasks
            windows-node12:
              environment_variables:
                NODE_VERSION: 12
              elastic_profile_id: windows-all
              tasks:
                - *windows_examples_tasks
      - functional-tests:
          environment_variables:
            TAIKO_HIGHLIGHT_ON_ACTION: false
          jobs:
            linux-headless-node8:
              environment_variables:
                headless: true
                NODE_VERSION: 8
              elastic_profile_id: ubuntu-node
              tasks:
                - *headless_functionaltest_tasks-linux
              artifacts:
                - build:
                    source: test/functional-tests/reports/html-report
                    destination: reports
            linux-headless-node10:
              environment_variables:
                headless: true
                NODE_VERSION: 10
              elastic_profile_id: ubuntu-node
              tasks:
                - *headless_functionaltest_tasks-linux
              artifacts:
                - build:
                    source: test/functional-tests/reports/html-report
                    destination: reports
            linux-headless-node12:
              environment_variables:
                headless: true
                NODE_VERSION: 12
              elastic_profile_id: ubuntu-node
              tasks:
                - *headless_functionaltest_tasks-linux
              artifacts:
                - build:
                    source: test/functional-tests/reports/html-report
                    destination: reports
            linux-headful:
              environment_variables:
                headless: false
              elastic_profile_id: debian-node-xvfb
              tasks:
                - exec:
                    command: npm
                    arguments:
                      - install
                - exec:
                    command: xvfb-run
                    arguments:
                      - npm
                      - run
                      - test-functional
              artifacts:
                - build:
                    source: test/functional-tests/reports/html-report
                    destination: reports

            windows-node8:
              environment_variables:
                headless: true
                NODE_VERSION: 8
              elastic_profile_id: windows-all
              tasks:
                - *headless_functionaltest_tasks_windows
              artifacts:
                - build:
                    source: test/functional-tests/reports/html-report
                    destination: reports
            windows-node10:
              environment_variables:
                headless: true
                NODE_VERSION: 10
              elastic_profile_id: windows-all
              tasks:
                - *headless_functionaltest_tasks_windows
              artifacts:
                - build:
                    source: test/functional-tests/reports/html-report
                    destination: reports
            windows-node12:
              environment_variables:
                headless: true
                NODE_VERSION: 12
              elastic_profile_id: windows-all
              tasks:
                - *headless_functionaltest_tasks_windows
              artifacts:
                - build:
                    source: test/functional-tests/reports/html-report
                    destination: reports
      - publish:
          approval: manual
          jobs:
            publish:
              elastic_profile_id: ubuntu-node
              secure_variables:
                NPM_TOKEN: AES:smCSdWEkiHlJgx9yY+uCQQ==:oJgEJ1fMOzrQ7Ot62KcOj8dqPFKApy8X2E19uy793RzIl1NEi3JTTbHGn2CyH6ew
              tasks:
                - exec:
                    command: npm
                    arguments:
                      - install
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}'>~/.npmrc && npm publish
            github:
              elastic_profile_id: centos-all
              environment_variables:
                GOPATH: /tmp
                repoName: taiko
                uploadArtifact: no
              secure_variables:
                GITHUB_TOKEN: AES:5M8sxVr62XcjB5nQXkByQA==:2htgkabgxfyPGtwzwUmKI8Aa4V3gg/kA9hSpMw+Z+wTScfcWrHHYH9mEMQbZ21IP
              tasks:
                - exec:
                    command: build/github_release.sh
