pipelines:
  VSCode-Build:
    group: IDE_Plugins
    materials:
      gauge-vscode:
        git: https://github.com/getgauge/gauge-vscode.git
        shallow_clone: true
    stages:
      - build:
          jobs:
            build:
              elastic_profile_id: debian-node-xvfb
              environment_variables:
                GAUGE_ROOT: /tmp
              tasks:
                - exec:
                    command: /bin/sh
                    arguments:
                      - -c
                      - npm -v
                - exec:
                    command: /bin/sh
                    arguments:
                      - -c
                      - npm run build
              artifacts:
                - build:
                    source: gauge-*.vsix
                    destination: artifacts
                - build:
                    source: "*"
                    destination: gauge-vscode
  VSCode-Tests:
    group: IDE_Plugins
    materials:
      vscode-build:
        pipeline: VSCode-Build
        stage: build
      gauge-package:
        pipeline: Gauge-Build
        stage: windows
    stages:
      - test:
          jobs:
            linux:
              elastic_profile_id: debian-node-xvfb
              environment_variables:
                GAUGE_ROOT: /tmp
              tasks:
                - fetch:
                    pipeline: Gauge-Build
                    stage: windows
                    job: sign
                    source: test_installers/gauge-linux.x86_64.zip
                    is_file: yes
                - exec:
                    command: /bin/sh
                    arguments:
                      - -c
                      - mkdir -p $GAUGE_ROOT/bin && unzip -o gauge-linux.x86_64.zip -d $GAUGE_ROOT/bin
                - exec:
                    command: /bin/sh
                    arguments:
                      - -c
                      - PATH=$GAUGE_ROOT/bin:$PATH gauge config gauge_repository_url https://raw.githubusercontent.com/getgauge/gauge-nightly-repository/master
                - exec:
                    command: /bin/sh
                    arguments:
                      - -c
                      - ($GAUGE_ROOT/bin/gauge install js && $GAUGE_ROOT/bin/gauge install html-report && $GAUGE_ROOT/bin/gauge version)
                - fetch:
                    pipeline: VSCode-Build
                    stage: build
                    job: build
                    source: gauge-vscode
                - exec:
                    working_directory: gauge-vscode
                    command: /bin/sh
                    arguments:
                      - -c
                      - rm -rf node_modules && npm run build
                - exec:
                    working_directory: gauge-vscode
                    command: /bin/sh
                    arguments:
                      - -c
                      - PATH=$GAUGE_ROOT/bin:$PATH xvfb-run npm test
            darwin:
              resources:
                - UT
                - darwin
              environment_variables:
                GAUGE_ROOT: /tmp
              tasks:
                - fetch:
                    pipeline: Gauge-Build
                    stage: windows
                    job: sign
                    source: test_installers/gauge-darwin.x86_64.zip
                    is_file: yes
                - exec:
                    command: /bin/sh
                    arguments:
                      - -c
                      - mkdir -p $GAUGE_ROOT/bin && unzip -o gauge-darwin.x86_64.zip -d $GAUGE_ROOT/bin
                - exec:
                    command: /bin/sh
                    arguments:
                      - -c
                      - PATH=$GAUGE_ROOT/bin:$PATH gauge config gauge_repository_url https://raw.githubusercontent.com/getgauge/gauge-nightly-repository/master
                - exec:
                    command: /bin/sh
                    arguments:
                      - -c
                      - ($GAUGE_ROOT/bin/gauge install js && $GAUGE_ROOT/bin/gauge install html-report && $GAUGE_ROOT/bin/gauge version)
                - fetch:
                    pipeline: VSCode-Build
                    stage: build
                    job: build
                    source: gauge-vscode
                - exec:
                    working_directory: gauge-vscode
                    command: /bin/sh
                    arguments:
                      - -c
                      - rm -rf node_modules && npm run build
                - exec:
                    working_directory: gauge-vscode
                    command: /bin/sh
                    arguments:
                      - -c
                      - PATH=$GAUGE_ROOT/bin:$PATH npm test
                - exec:
                    run_if: any
                    command: touch
                    arguments:
                    - /vagrant/rollback.txt
            windows:
              elastic_profile_id: windows-all
              environment_variables:
                GAUGE_ROOT: C:\tmp
              tasks:
                - fetch:
                    pipeline: Gauge-Build
                    stage: windows
                    job: sign
                    source: test_installers/gauge-windows.x86_64.zip
                    is_file: yes
                - exec:
                    command: cmd
                    arguments:
                      - /c
                      - unzip -o gauge-windows.x86_64.zip -d %GAUGE_ROOT%
                - exec:
                    command: cmd
                    arguments:
                      - /c
                      - "%GAUGE_ROOT%\\gauge install screenshot"
                - exec:
                    command: cmd
                    arguments:
                      - /c
                      - "%GAUGE_ROOT%\\gauge config gauge_repository_url https://raw.githubusercontent.com/getgauge/gauge-nightly-repository/master"
                - exec:
                    command: cmd
                    arguments:
                      - /c
                      - "%GAUGE_ROOT%\\gauge install js && %GAUGE_ROOT%\\gauge install html-report && %GAUGE_ROOT%\\gauge version"
                - exec:
                    command: cmd
                    arguments:
                      - /c
                      - "%GAUGE_ROOT%\\gauge -v"
                - fetch:
                    pipeline: VSCode-Build
                    stage: build
                    job: build
                    source: gauge-vscode
                - exec:
                    working_directory: gauge-vscode
                    command: cmd
                    arguments:
                      - /c
                      - rmdir /S /Q node_modules & npm run build
                - exec:
                    working_directory: gauge-vscode
                    command: cmd
                    arguments:
                      - /c
                      - path %GAUGE_ROOT%;%PATH% & npm test
  VSCode-Deploy:
    group: IDE_Plugins
    materials:
      vscode-build:
        pipeline: VSCode-Build
        stage: build
    environment_variables:
      GOPATH: /tmp
    stages:
      - github-release:
          approval: manual
          clean_workspace: true
          jobs:
            release:
              elastic_profile_id: centos-all
              environment_variables:
                repoName: gauge-vscode
                artifactName: gauge
              secure_variables:
                GITHUB_TOKEN: AES:bI2YOl21056SfErCsMNAAw==:yB9Cacb8aOx4+g1gLO1qDLFomeMaoZzT6UEi7hK460Ynf/fKirmEn+QMltDsWqB7
                username: AES:VOC7MIlHxgMYXpv/9H6kCg==:UXG2r0NTvfAdgAHwZu+Xfw==
                password: AES:74P92aYQsuotGroK/uSfPQ==:UJgVH9rwuOKLhq1hmg/PzQ==
                GITHUB_SSH_PRIVATE_KEY: AES:WufQ+0lOQDuPb9Zf65Liqg==:srnE2wCb6scFsQf9+zWnF6KT8PerOqGY+dUx3BVG6UDsOYIIRcgpiPgEVsnX+LtEccB6aTYzwhbcBijikG3wnf+anWOk5163DvME8GKJxua53AuwTN82LVsyKY2mDL9Of3DK7Fvusbcy/1Sgep4m5j25xDPybCcCFoEB5p5sJbY5gVrsK8cuzMe+U0k9+8HUui5KobzxxzWld4Wf3/GeSodDQtVyxxyeA8YjC05UAVOgitrmcBlMgDX+U24MBxIgEG61gUCE0Sz3nvnURgYDCMJXQKLM9bhOeWGdiht3eI561lBE0o9K4PinUXwJKTToifFYpEbnzsrnhsuLIvHZL/OmP0dJJck8T2b8CrK4v5SOOprTHeQBrpyvZWDVbpJ9ID2Mz1wEROCbX7l8RYYnNtQIkUtuQlqBbH7FnesrMdPsEnHDHg70eWoza8sDZWWBwaW71WwkGD5+83h/nvcwiabu64EnT9xjNs2vYFB1vCqLWbfOngAUZknSd3vvIMbEXOi40ZXoMrXEnQG2ye+w3xY7sljmaFwD2+vd0x3ybM/i0zdjlINkUsu3v3q/7hxdvOAKDD4y6nUfHrvJe5HCvyAFGR0uYtzKC3J+sT67rL/i/DH2sJhcBwIE/FDfgBnN5mfrW22j+bQ+f8e+fWdRAwvtOWmhL1U4kJxtSxZL7kucbXAvGZSC9puPq2sYBS6rj00MWMBVcHyKhJNN1Ev3J+x3Fohk6zbjHeUaeQ1BU3FuCGb2bm+UvT4bj78Q3gm1EaOx90ZQ9yaTrMO+neiY/AVLFkSOXG0DSUrZDBFd7z9BdQ4WgNQjaa3ZCtlHvnpEy+c8dRiPjwCyc0f6iruIajqBRlKfh9Fd/zNvuAoA/VGS4ZqIhKSmR4ixaHpMAbfslhQ6K6Exn5fmDIxmipSSqmDIDt0lwzSGmqce25Ow8A7nn6goPg5wlHHrZfVa01jrSAvVGGzWPdoXsHh4foJzV64or/PLMOdSajRVU5nI45wgHbgrI9UmRMVXC+FtePywr6Agl1kr/x/0oxnwEACZBk+x3v80YTVQkyjhGxPW1s/BnfoVnibWvfhDeUNE48c1kObyRN/qXUqBBVJKIm1/ZQ9o8TK84TuaLWvlF9Nfp5CmQaLdNDGPiqzpTkVpa6HFOtRqy6oS4JszvsVunVb0f34ulA4Q2CCkxb8Zt4SHuZg3wqClsHdZqumOXJYZkqS/voYuiXpRJyUI/NNbo2o6cM3VPCy4wJFG592JACG9sNRzsRo2TeUQk/gev+fHNcbqP4rH+d1xjbsrqrgQkdGPmLAWWTa5tc7mtjdpC2KLFSM/Y1K3rrpXzhO2M+070sIEdQAoRmiZFRxuXELBllm9rfewp3a4Hdazl1GLuE1zzsPqGZDqL3e554c/PkakoPKO/V8ZX1FnVgRWTC+panHuaFLL1pHt2ObRhuwHbycmVS3tfRJ7xSHlOZV9O3YtjrOdRXL0pIagcMY9u9Lw3LqHLrIOn4EDTXFNZT+1pndDQwF6fpq7aO9Z2WHMZtp9DgerVp3Zz7OrkqJHiYRk5wt5zgHnIpd3dTuNYLfsb3YfnanZ/4kg+5bZKY/GbSC5Iz5Yt7D4e4aD9sUrGITNoYpHcwLM0SVkJdvGfLKvN1lEHPcr3PPbfR8rxxjy5mIUIJJmXJDjHph72U8NkLM1ujglkg2dXzcGdHqvTtHHFAhel38dab4trQjZ/ENPwiRq5t44C+7a4NR8ngN3VbXtYbq09SfSdp08XbKNdXapIUjM39okzlryd2tnjD6EhibfoyOJg7SKmr3F/cMNs8UBRJ4Uxr3W94TFvSsXDb1LJ+dYcniV2OUyhFWTqKR376QF/2aZPbj7EXwKJPJ6xZQjWTssLOT4zwxtteolxYxlJqYSZiw7jrfANo26+v7cCYSZ2USAEMFpgtB6jzlZFshZysGOnQD4mh9SCd7iyMjMa39zid2H6QuyLBQB8bpiwOba90xONJClR6RDuEMvZ1tmP7sYN4ZttRa+M4kYYfZfuuQXaI5HXMKJFQk/uK6h3x7jELuul7gwCjtMg2YS1GmL+6iaMl0UVDHUblNBTMHKwtQuv+5n6BpwX2BwoBeJOaEF9HWlaqlxtM6GNNqajrZ77cp1vShQYt5XYJVmVDV3gU5bRduos3UwHLfxBP3Oruts9P/Wg1utfQIS6t+s+agSbOyn795m37lNdOI+zxLCFGNnzZYX3zKQYMO4lqkJ9tyxqDg7yUjbXiufyrmJT8V/20YXl4YLC0Xz+QoMvKXZpO0oPQ40wH5zlLkorihTUeC811e6XGIHxAeHLPDjYqdaKUsANkKQzBUztf+jQxPf7A3ztYtwQ8hei6opCi2vnBJyz4Dp41C19YZ0tlWBI1edR8d4XI3DyOd2kU5zfQzf2kb4lvZ21/2rk3jqIQ1oI4mkB4kqf0ENjXPQ0osjQICiUa5UFcNwi5WT8FcoffimQJxhzKikxIwD0wggBINSvuB2R1qXgJt4zsXM2OtTxO3PHAcSTmKxsYMg0MB0aBGYtOk0LEhVUZYOnM2M7y4hyBTbqa15z210tx4oEZKD+EExYz+vaX57G4zVPLkk+b17oVaf8wJ9IzpVZg/7cZtF4YD2nckcOGdIHddBvFExdbdWeckDltZZjfaoeAU1FDc7BaRLGz+b/USC+YpbeF9pVnFdPjRX77GLYZlSeWKP/wGxmTXbv53jgg9gMJ6TA2plmjelyeYq+vPnpWKMZ56Z7qq9H+dPiRkse+Mdog5+IIzr0QbvfYuIBK5Dmnv5cdQFBHrru5ATvtbyhiK68H/WOG5ZDjUumDu4/4U5spvDYT0bWpzggAyKZ7v5CfTPpBztJ+hzRNPTJqXPNK6ajfHszIJz23M1w1cfnaVBH+GownzcQXI+7+6ZNzDKFnVVCsRgl6nUw4IwxtLCvv3R40O57gqAUFFrp9aFC2M36POocJtEhsiUiCjkDmTiXH0fKOygiRR/SP7SX1s0x+637JVGLSkPt0h/LtSURNLLiOs+QMGUSrW99AmKbIY9mhCVyX3kJd5KX65YBw+UsgiHhvETYFEeiFqvPR42zpy896tDZ/Diahubd0+ecj1gl90zigVXIt3APtSPEbaSIzInsjuBsPZTlY9+VhFfRZVhIvlrHisASXkCQLeE9O01mM9UQ3leN1ykHI3gkHyFem66teejySNS4Ix1sHW6eWcCFiDlnqvDLhdL0tSjmOFGpIN13rccRq+IPKXH84uYP006irgON/TPvskkkJY1KKmA4+gl33JE0ZfUFZIWUBWqCTOtfMSFIQYabnYcvB7xkxG/GhgnpzrNl7exfsgXj//s6pcbBBgPLC21U4nsYFCyrzRBi4vSkZepfYsGHfSMu064Yz9J/biyuo4+ioBtoqjybJ8xlSAx9atSi7Bq2LWoKOs8Ec1JYyzkvSq/n3l2QMipO9HbZNb9ttxzkiwR7+eUvG0yThrJSLqKfnLa8bs2DA2tO6yKLH4sK/IuDR2lNHpUuyitHLp8Tb6NlDGzyEPP0JVqHzsN9LOaRRL6jAMh2JmHJgnKKj1MYwz+AOcm4Dp3bBadJLfbPz1Br+SY+glB3vWMiHd1QJzR4n/NWnVXQ8ijDpgBKbK4GizTYGYr3xWymfuMu0WHoD06ZNFpnrTT2Nr6q3/Nopoy3vsqt6ir/eFWajMdrBPP6o4AnmXkX2XDdBoeGpxjIWkU9jq5QgeID/gR59jnK+M1ozajIuoqr40sqhYQ48PmZlpHhv3Wl6Hwf9ekpQxSFghUEAVNMJmsreqWGBOPcdqBdCBgOhgbsqzILZF0teM+pmAA8us4JWKVd/aczY/WG3ftJoBLV5TD8xGBgAtiXSH7H9gYufpxiS/KrO8+wxv3dFFB7dINfyCv4UaAkW6qT3bPECAv4Sq3mJ9ZU2DUJ67Ul9WyEjzWcp7jfg2Caps+V+/MiqxHcRvhzdeQTN2+DNkPCcF2HCiZ3u//Ru39CnRHYsdknCdsr2m58UE8mVP5sUlJtb36oDjRsZa4eNSu4WAWQwqCU5khj4ITOpZOBCevYa1mOSiZiaOXOPhDLdoB4HqSVl4wt+huI4ZjGDFuDAECv5pZ5j4UHS676X2rjqA92W9IAa3a8pdqPDlPK8VwYGTR29JyzM1zhIL0Twct3SeODStyQYzF6GLOsuXvLqlhzDZ4lPXQJhL8getKi7X4FoFaiDlDinyitU1BCYwPDaHXHp3nURDso4sRT001mikkp1Q4m7ErBo6X/gXdi87E6WjOhX2mc+kRWZT6V4LzSyVqQwxFAlZb3m9UxFb2gxTaF6uDURQCc+KflxcjhwIgifQ=
              tasks:
                - fetch:
                    pipeline: VSCode-Build
                    stage: build
                    job: build
                    source: artifacts
                - exec:
                    working_directory: artifacts
                    command: /bin/sh
                    arguments:
                      - -c
                      - (curl -sSfL https://github.com/getgauge/gauge/raw/master/build/github_release.sh | sh)
      - release:
          clean_workspace: true
          jobs:
            publish:
              elastic_profile_id: centos-all
              secure_variables:
                VS_PAT: AES:ifCI6OQNqdDhSy9+z87xpA==:OFkx/alt+INXuIPLT7XEDALy+ibltOHF/5/W7pds3QNdt5k91BUyvv+nlCk+81a3KTwneRy7YdMYpU1brHU30w==
              tasks:
                - fetch:
                    pipeline: VSCode-Build
                    stage: build
                    job: build
                    source: gauge-vscode
                - fetch:
                    pipeline: VSCode-Build
                    stage: build
                    job: build
                    source: artifacts
                    destination : gauge-vscode
                - exec:
                    working_directory: gauge-vscode
                    command: /bin/sh
                    arguments:
                      - publish.sh
