pipelines:
  gauge.org:
    group: Websites
    materials:
      website:
        git: https://github.com/getgauge/gauge.org.git
    stages:
      - build:
          jobs:
            build:
              environment_variables:
                DOCS_VERSION: master
                BASE_URL: https://preview.gauge.org
              elastic_profile_id: centos-all
              tasks:
                - exec:
                    command: rbenv
                    arguments:
                      - local
                      - 2.4.0
                - exec:
                    command: bundle
                    arguments:
                      - install
                - exec:
                    command: /bin/sh
                    arguments:
                      - -c
                      - (LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/rh/nodejs010/root/usr/lib64/ bundle exec middleman build --verbose)
                - exec:
                    command: /bin/sh
                    arguments:
                      - -c
                      - echo $GO_REVISION_WEBSITE > build/version.txt
              artifacts:
               - build:
                   source: build/*
                   destination: deploy
      - deploy-preview:
          jobs:
            aws:
              elastic_profile_id: centos-all
              secure_variables:
                aws_access_key_id: MsgNaRPRZFDlyccRoC5exAK9DfmTzzaT
                aws_secret_access_key: Ya/3nrdaiGyESQtV0VzXplN14zffxSFbvKY5YxGOmNM4ccsN7Omu0FMx7sH6bF8y
              tasks:
                - exec:
                    command: /bin/sh
                    arguments:
                      - -c
                      - mkdir -p $HOME/.aws/ && echo -e "[default]\naws_access_key_id = $aws_access_key_id\naws_secret_access_key = $aws_secret_access_key\nregion=us-west-2\noutput=json" > $HOME/.aws/config
                - exec:
                    command: aws
                    arguments:
                      - s3
                      - rm
                      - s3://preview.gauge.org
                      - --recursive
                - fetch:
                    stage: build
                    job: build
                    source: deploy
                - exec:
                    working_directory: deploy
                    command: aws
                    arguments:
                      - s3
                      - sync
                      - .
                      - s3://preview.gauge.org
                      - --cache-control
                      - max-age=604800,s-maxage=1800
      - build-live:
          approval: manual
          jobs:
            build:
              environment_variables:
                DOCS_VERSION: latest
                BASE_URL: https://gauge.org
              elastic_profile_id: centos-all
              tasks:
                - exec:
                    command: rbenv
                    arguments:
                      - local
                      - 2.4.0
                - exec:
                    command: bundle
                    arguments:
                      - install
                - exec:
                    command: /bin/sh
                    arguments:
                      - -c
                      - (LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/rh/nodejs010/root/usr/lib64/ bundle exec middleman build --verbose)
                - exec:
                    command: /bin/sh
                    arguments:
                      - -c
                      - echo $GO_REVISION_WEBSITE > build/version.txt
              artifacts:
               - build:
                   source: build/*
                   destination: deploy
      - deploy-live:
          jobs:
            aws:
              elastic_profile_id: centos-all
              secure_variables:
                aws_access_key_id: MsgNaRPRZFDlyccRoC5exAK9DfmTzzaT
                aws_secret_access_key: Ya/3nrdaiGyESQtV0VzXplN14zffxSFbvKY5YxGOmNM4ccsN7Omu0FMx7sH6bF8y
              tasks:
                - exec:
                    command: /bin/sh
                    arguments:
                      - -c
                      - mkdir -p $HOME/.aws/ && echo -e "[default]\naws_access_key_id = $aws_access_key_id\naws_secret_access_key = $aws_secret_access_key\nregion=us-west-2\noutput=json" > $HOME/.aws/config
                - exec:
                    command: aws
                    arguments:
                      - s3
                      - rm
                      - s3://gauge.org
                      - --recursive
                - fetch:
                    stage: build-live
                    job: build
                    source: deploy
                - exec:
                    working_directory: deploy
                    command: aws
                    arguments:
                      - s3
                      - sync
                      - .
                      - s3://gauge.org
                      - --cache-control
                      - max-age=604800,s-maxage=1800
  docs.gauge.org:
    group: Websites
    label_template: ${COUNT}
    materials:
      website:
        git: https://github.com/getgauge/docs.getgauge.io.git
      gauge:
        pipeline: gauge-deploy
        stage: docs
    environment_variables:
      LC_ALL: en_US.utf-8
      LANG: en_US.utf-8
    stages:
      - build:
          jobs:
            build:
              elastic_profile_id: centos-all
              tasks:
                - exec:
                    command:  git
                    arguments:
                      - version
                - exec:
                    command: virtualenv
                    arguments:
                      - docs
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - source ./docs/bin/activate && pip install -r requirements.txt && make zip && deactivate
              artifacts:
               - build:
                    source: _build/html/*
                    destination: deploy
      - deploy:
          jobs:
            aws:
              elastic_profile_id: centos-all
              secure_variables:
                aws_access_key_id: AES:dH5bwy34WSzQmUChLz5Sqw==:LCLuya+iy1vIuW5x1dBq1vKvHLfVMQncV6ABMdc+rFI=
                aws_secret_access_key: AES:+PTrCMdaQCEAdhFM5z6EjA==:qGiUjD9Y6B5mtzPocpCt5DyHF/JvVQVKu0i1iD0su4CX6Nbr5GQq/GDU4JemreC9
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - mkdir -p $HOME/.aws/ && echo -e "[default]\naws_access_key_id = $aws_access_key_id\naws_secret_access_key = $aws_secret_access_key\nregion=us-west-2\noutput=json" > $HOME/.aws/config
                - exec:
                    command: aws
                    arguments:
                      - s3 rm s3://docs.gauge.org/latest --recursive
                - exec:
                    command: aws
                    arguments:
                      - s3 rm s3://docs.gauge.org/master --recursive
                - fetch:
                    stage: build
                    job: build
                    source: deploy
                - exec:
                    working_directory: deploy
                    command: aws
                    arguments:
                      - s3 sync . s3://docs.getgauge.io --cache-control max-age=604800,s-maxage=1800
                - exec:
                    working_directory: deploy
                    command: aws
                    arguments:
                      - s3 sync . s3://docs.gauge.org --cache-control max-age=604800,s-maxage=1800
  insights.getgauge.org:
    group: Websites
    label_template: ${COUNT}
    materials:
      website:
        git: https://github.com/getgauge/insights.getgauge.io
        shallow_clone: true
    timer:
      spec: "0 0 0 1 * ?"
    stages:
      - generate:
          approval:
            type: manual
            roles:
              - XD_UI
          secure_variables:
            GA_PRIVATE_KEY: AES:eVIFOtOYyv9l0hOMqXVYBQ==:Q+kyTUgwrdR71HnBt0o1oj5UGl3r+N6NHo6A2p+W2XI0W1xioMECceUBUHq+n87fgGgFqxGTNKs3YIow6kFOgNpfsRqVD7k7E4InKnBMJIsdhxm9F6+lYngDoslys/uLtg5FSGziSCsZXAGkJLw+/Qn27sd6ISzgopT7IgSYbMzf56QIhCeT21E8O87Z8jnKb6vF0lDcsVeSTmgi6H21HQD3BIYuvOP37ZjaYPUjKXSKQG5Of4Xkbkguk8bzOMZXs1P2UD1Rb5kzcjEgxI4ReLOoYcIk0U2k7gyTb3F4CfIZuw8ntbOth7Y9KDlf5119nAFi2IivHF2zimxUMcv1rGUX8x+pUHrNPVWJia1Prhl9xldHquM/IcJuBYMT6P/H7J0UlKISkgH9T++qWZyBM6cKOqtwGqGbe5dcgoJm6+o2cOVOpJUHhmEDxbFZO9hcqYilkW5tXdd1U3fk5LJXGOEY/KDt8JZs+H2X6QCROFJXC/akXLfCNBzNA84xXYhx23GlUr+lwJbMhKaTo9Iti5lZGhukOV0dCNmqYqMaftoeLUDxS02c9cwDsoHYpZo1K3M9c8oFICLGQQYIgE+kRUp1PDUSFVbR0+Zm8aTYx7iSssKjxZFqlyRlaEiawYIKL9+iQVM35zfsPZWpFFrW7cDsnZEJ1SC0/uccVgNp6fJJSrYPdiURrsjxMTXg0ILKLDj53HC9Fg52A48YuaxgUTJQF52kBueLglWzdP7nnhXyEOGOsF0WXvYIkI3K4ojD44AaH0qsvAVLExf7s+NFT1MSp4oEk5gtFeKpxptl9QfzfGC9I/BJwZYS2+IUqzGLgPkYurnDKaU8hkyxz/2PiPA1cf7xX4SI/Ptts+qitO3qGXDbR8Ktj3sOu6YIIkN9CaiqirN9sKjfd+2cCEIS2z+9sFimuySEpCANp+NFcm8ev1zcs7WcsO/Z1sPWkp2Z7Wq/dr39AwSZAT2pKODXKAcLa2DBJo6pWmPesTuVjKIP7fu1JH+xNvTE+ynNPLTmH0uKWYAfBS1fJEdZZss7V6BM0Kdzeq+1uCZI+0YI19+YpAIIe9LUrd+KmPOhBuCSh4dCWz7P8KhNokxfe3ARxAyDOCTppLNaUkPzGerJlE+1ycuLjWeZTs0gpfJvL1/tjN5kA8g6uNoVQy6e6lJ+PaUoR1rf38y+9dDF/IfnfjspS9/3DOlJpJL90cGaaUUA+VdXzHSwYT2myhs1Ck/w3SDMcC6rFY4RF7CZbZHLrBkw83IaZbNO2K0ir1cP3a5EtTgv3iBVvwGGz0oeomx2qstEs8HuL5/HeYTsE8ho94a3mbFchb27AfzVJ4NJiXCoZrY9H10Wk/rdktN8xEqbjNDTZsll9WZ83WhFUQbTyuUaSnN9CAZbGAXPFLhMvd9uQ68StWPnxdgxUvk1yV50mt5Hn1od1yBjrOklwZnJLahsyPbyb5s47A19NR0NiC2qYcVcWkoQD34zuAJjdRPCmkZGZUORP4ptm3EV0epCPm8cR/db/TZIG3cPUMrPQAd6u9kggn06AZSNtuIESaRDbCVjG0WfqZZ29BqsXuBwV8+IrtpZL5kTcz6gDSUSs2V8m8Q/Hcz0tVWRm9YFRiEsZJzLOSIUWOvhNv7AC4aYAro5kT2AqSy+rTvNKM0khjR2+PhIpgmNuIyNx+FTroRvnlKxqivjH0guwEzcyjBZWwdrSNC5sA6ZQIBnzs/8Ax7hEdSWhFnIOoDgXyYUFiSN5Vmr9wWX3f0U6vbCnXqK0IEpW2rr6+ytpChqr6ppZ8vVU8Jgy8c0YMxTRtfMkZ4hoW+vWtP7X3I8QX2soa4xiDro0y2ArDETz9fmp4OXk3HVr8LIxUVW5K4WbtCfa+A5mk2dz0RTr3hSuxmS2Ts2a8TsYSlMd0x8bhiWzR84G1tou4sWgg4XocJh51x1lNKDZNRecy9vkDx2UmbUlMv0afAIrokUUklIrLAfhzBUhH97dJ2cOG4YhbkHNfFW7d8EdPMKsko7UUzEzqyIYCXcLPxSKLOy6UjAIoEJawmIbKiN8cG9gNo88sMvkBLXQmNX1Kd+zdbtbwnisj4xCCqRZJNT87xQ2wyV29nlV1AYSt0AjYECB29wFsyOpMtPKQU4PMKUAgvDEV8KpqW3ZOV8HjrRimfl/QQlEH1gwbLIh+YorFU90RBL11aSPgMw/84TBLm3dcLrImzkTU7ynLN2glwck3EYhI6rkURuX91cFFEOU38qolyHrfWSNdvnK0nXL5Lp+I3Ht7XgVtPmwkC1q1Hau1IpjUgqn70YRbC2F4fgGopRzN0yhk2nHI6ajgi95Q==
            GA_TOKEN_URL: AES:GPtyDEYtKH8zcuEkd8ArgA==:r16Ly/RbMLNiZ48Ks8zKwniY302k0anYkewvGkI/LLJFm26PTLgdJGuksli9UsRK
            GA_SERVICE_ACCOUNT_EMAIL: AES:n+hOh3bKo3G9xP87YNvaNQ==:BoYquLo8gi7MjBNU9MP9SkjUeOPgTzXLqv8aZ54vJICEzMMOAsUxG31F6rMcHyg0
            GA_VIEW_ID: AES:08jh0UQiBkpgstxlBohfyw==:3yKo1GaY54hcl3eEpdcNEA==
          jobs:
            build:
              environment_variables:
                GOPATH: /tmp
                GOBIN: /tmp/bin
              secure_variables:
                aws_access_key_id: AES:mKN0uKAs3tl4H70/HVT03Q==:d0/TQpXj5/wrE0XTbkZKFwys8xw0PVAKdiqqwsLLWe4=
                aws_secret_access_key: AES:P1KpYujyy8Ad2OZ8GIODMw==:wgnycSK+462+TKiuIOhYxjeR0J1dTOy268iKUbOniSwitdXqF9h2J0m9kjOW9e8p
              resources:
                - codesign
                - darwin
              tasks:
                - exec:
                    command: /bin/sh
                    arguments:
                      - -c
                      - go get -d -u -t -v github.com/getgauge/insights.getgauge.io
                - exec:
                    command: /bin/sh
                    arguments:
                      - -c
                      - (cd $GOPATH/src/github.com/getgauge/insights.getgauge.io && echo $GA_PRIVATE_KEY > ga.pem && go get ./... && go run *.go)
                - exec:
                    command: /bin/sh
                    arguments:
                      - -c
                      - (cd $GOPATH/src/github.com/getgauge/insights.getgauge.io && rm ga.pem)
                - exec:
                    command: /bin/sh
                    arguments:
                      - -c
                      - mkdir -p $HOME/.aws/ && echo "[default]\naws_access_key_id = $aws_access_key_id\naws_secret_access_key = $aws_secret_access_key\nregion=us-west-2\noutput=json" > $HOME/.aws/config
                - exec:
                    command: /bin/sh
                    arguments:
                      - -c
                      - aws s3 rm s3://insights.getgauge.io --recursive
                - exec:
                    command: /bin/sh
                    arguments:
                      - -c
                      - (cd $GOPATH/src/github.com/getgauge/insights.getgauge.io/_insights && aws s3 sync . s3://insights.getgauge.io --cache-control max-age=604800,s-maxage=1800)
                - exec:
                    command: /bin/sh
                    arguments:
                      - -c
                      - aws s3 rm s3://insights.gauge.org --recursive
                - exec:
                    command: /bin/sh
                    arguments:
                      - -c
                      - (cd $GOPATH/src/github.com/getgauge/insights.getgauge.io/_insights && aws s3 sync . s3://insights.gauge.org --cache-control max-age=604800,s-maxage=1800)
                - exec:
                    command: touch
                    arguments:
                      - /vagrant/rollback.txt
  manpage.getgauge.org:
    group: Websites
    label_template: ${COUNT}
    materials:
      Gauge:
        pipeline: Gauge-Deploy
        stage: docs
    stages:
      - deploy:
          jobs:
            deploy:
              elastic_profile_id: centos-all
              environment_variables:
                GOPATH: /tmp
                GOBIN: /tmp/bin
              secure_variables:
                aws_access_key_id: AES:8Trjf9FYyI3Nx/tjYyrtHA==:G9NNxbIs0aR69ExYTAgEzFt291I6D/Va8ZMWUaqkKCk=
                aws_secret_access_key: AES:/nHkQyp0aZxELF7VZbMf8Q==:mqAEnub+UmvdA5IwpQjg1TdQ4P5c7D6IR9ozDZV3JbCUFx3uMOLQWrF2yRJw4MIN
              tasks:
                - exec:
                    command: /bin/sh
                    arguments:
                      - -c
                      - go get -d -u -t -v github.com/getgauge/gauge
                - exec:
                    command: /bin/sh
                    arguments:
                      - -c
                      - (cd $GOPATH/src/github.com/getgauge/gauge && go get ./build/man/ && go run build/man/man.go)
                - exec:
                    command: /bin/sh
                    arguments:
                      - -c
                      - mkdir -p $HOME/.aws/ && echo -e "[default]\naws_access_key_id = $aws_access_key_id\naws_secret_access_key = $aws_secret_access_key\nregion=us-west-2\noutput=json" > $HOME/.aws/config
                - exec:
                    command: aws
                    arguments:
                      - s3 rm s3://manpage.getgauge.io --recursive
                - exec:
                    command: aws
                    arguments:
                      - s3 rm s3://manpage.gauge.org --recursive
                - exec:
                    command: /bin/sh
                    arguments:
                      - -c
                      - (cd $GOPATH/src/github.com/getgauge/gauge/_man/html && aws s3 sync . s3://manpage.getgauge.io --cache-control max-age=604800,s-maxage=1800)
                - exec:
                    command: /bin/sh
                    arguments:
                      - -c
                      - (cd $GOPATH/src/github.com/getgauge/gauge/_man/html && aws s3 sync . s3://manpage.gauge.org --cache-control max-age=604800,s-maxage=1800)